force-app/main/default/objects/Negotiation_Checklist__mdt/Negotiation_Checklist__mdt.object-meta.xml
<CustomObject>
    <label>Negotiation Checklist</label>
    <pluralLabel>Negotiation Checklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Additional_Value__c.field-meta.xml
<CustomField>
    <fullName>Additional_Value__c</fullName>
    <label>Additional Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Datatype__c.field-meta.xml
<CustomField>
    <fullName>Datatype__c</fullName>
    <label>Datatype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <label>Default Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disclaimer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/IsHeading__c.field-meta.xml
<CustomField>
    <fullName>IsHeading__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsHeading</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/IsMainHeading__c.field-meta.xml
<CustomField>
    <fullName>IsMainHeading__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsMainHeading</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/IsSubLabel__c.field-meta.xml
<CustomField>
    <fullName>IsSubLabel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSubLabel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Sub_With_single_column__c.field-meta.xml
<CustomField>
    <fullName>Sub_With_single_column__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sub With single column</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Negotiation_Checklist__mdt/fields/Text_Label__c.field-meta.xml
<CustomField>
    <fullName>Text_Label__c</fullName>
    <label>Text Label</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GetNegotiationChecklistMetadata.cls
public class GetNegotiationChecklistMetadata {
    @AuraEnabled(cacheable = true)
    public static List<Object> execute(){
        List<Object>returnList = New List<Object>();
        List<Negotiation_Checklist__mdt	> negotiationCheckList = [SELECT Id,Label,MasterLabel, Additional_Value__c, 
                                                                                  IsHeading__c, IsMainHeading__c, 
                                                                                  IsSubLabel__c,
                                                                                  Sequence_No__c,
                                                                                  Text_Label__c,Datatype__c,
                                                                                  Default_Value__c,
                                                                                  Sub_With_single_column__c,
                                                                                  Disclaimer__c,
                                                                                  Location__c
                                                                                  FROM Negotiation_Checklist__mdt	 
                                                                                  ORDER BY Sequence_No__c ASC]; //ORDER BY Sequence_No__c ASC
        
        system.debug('negotiationCheckList'+negotiationCheckList);
        if(!negotiationCheckList.IsEmpty()){
            for(Negotiation_Checklist__mdt mdt :negotiationCheckList){
                returnList.add(mdt);
            }
        }
        return returnList;
    }
    
}