force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <label>Current Stage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Previous_Stage__c.field-meta.xml
<CustomField>
    <fullName>Previous_Stage__c</fullName>
    <label>Previous Stage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityHandlerTest.cls
/* 
     *@description       : Whenever the deal breaks in the path, we should know in which stage it was breaked test class
	  @author            : Ruban
	  @last modified on  : 29/04/2025
      
*/

@isTest
public class OpportunityHandlerTest {
   @isTest
    static void testOpportunityStageTracking() {
        
        Opportunity__c opp = new Opportunity__c(
            Name = 'Test Opportunity',
            Stage__c = 'Site Visit' 
        );
        
        Test.startTest();
        insert opp;
        
        opp.Stage__c = 'Qualified'; 
        update opp;
        Test.stopTest();

        Opportunity__c updatedOpp = [SELECT Id, Previous_Stage__c, Current_Stage__c FROM Opportunity__c WHERE Id = :opp.Id];

       
        System.assertEquals('Site Visit', updatedOpp.Previous_Stage__c, 'Previous Stage should be Site Visit');
        System.assertEquals('Qualified', updatedOpp.Current_Stage__c, 'Current Stage should be Qualified');
    }
}