force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PeB</fullName>
            </value>
            <value>
                <fullName>RCC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Built_up_area__c.field-meta.xml
<CustomField>
    <fullName>Built_up_area__c</fullName>
    <label>Built up area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Ceiling_Center_Height__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Center_Height__c</fullName>
    <label>Ceiling Center Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Ceiling_Side_Height__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Side_Height__c</fullName>
    <label>Ceiling Side Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Advance_Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Advance_Security_Deposit__c</fullName>
    <label>Advance Security Deposit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>PEB</fullName>
            </value>
            <value>
                <fullName>RCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Built_up_Area__c.field-meta.xml
<CustomField>
    <fullName>Built_up_Area__c</fullName>
    <label>Built-up-Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Canopy_available__c.field-meta.xml
<CustomField>
    <fullName>Canopy_available__c</fullName>
    <label>Canopy available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Center_Height__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Center_Height__c</fullName>
    <label>Ceiling Center Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Center_Height_UOM__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Center_Height_UOM__c</fullName>
    <label>Ceiling Center Height UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Side_Height__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Side_Height__c</fullName>
    <label>Ceiling Clear Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Side_Height_UOM__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Side_Height_UOM__c</fullName>
    <label>Ceiling Side Height UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Dock_Leveller__c.field-meta.xml
<CustomField>
    <fullName>Dock_Leveller__c</fullName>
    <label>Dock Leveller</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/EoT_Crane_Provision__c.field-meta.xml
<CustomField>
    <fullName>EoT_Crane_Provision__c</fullName>
    <label>EoT Crane Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <label>Escalation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fire_Noc_available__c.field-meta.xml
<CustomField>
    <fullName>Fire_Noc_available__c</fullName>
    <label>Fire Noc available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fire_Safety__c.field-meta.xml
<CustomField>
    <fullName>Fire_Safety__c</fullName>
    <label>Fire Safety</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extinguishers</fullName>
            </value>
            <value>
                <fullName>Hydrants</fullName>
            </value>
            <value>
                <fullName>Sprinklers</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor_ht_from_ground_level__c.field-meta.xml
<CustomField>
    <fullName>Floor_ht_from_ground_level__c</fullName>
    <label>Floor ht from ground level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor_ht_from_ground_level_UOM__c.field-meta.xml
<CustomField>
    <fullName>Floor_ht_from_ground_level_UOM__c</fullName>
    <label>Floor ht from ground level UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Flooring_Strength_per_MT__c.field-meta.xml
<CustomField>
    <fullName>Flooring_Strength_per_MT__c</fullName>
    <label>Flooring Strength (per MT)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/No_of_shutters__c.field-meta.xml
<CustomField>
    <fullName>No_of_shutters__c</fullName>
    <label>No of shutters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Office_space_available__c.field-meta.xml
<CustomField>
    <fullName>Office_space_available__c</fullName>
    <label>Office space available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Power_available__c.field-meta.xml
<CustomField>
    <fullName>Power_available__c</fullName>
    <label>Power available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Rent_per_uom_Price_per_uom__c.field-meta.xml
<CustomField>
    <fullName>Rent_per_uom_Price_per_uom__c</fullName>
    <label>Rent per uom/ Price per uom</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/SIDCO_SIPCOT_CAM_or_Addl_Charges__c.field-meta.xml
<CustomField>
    <fullName>SIDCO_SIPCOT_CAM_or_Addl_Charges__c</fullName>
    <label>SIDCO / SIPCOT / CAM or Addl Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c.field-meta.xml
<CustomField>
    <fullName>SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c</fullName>
    <description>SIDCO/SIPCOT/CAMorAddl Charges SqFt/SqMt</description>
    <label>SIDCO/SIPCOT/CAM/Addl Charges SqFt/SqMt</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_Range__c.field-meta.xml
<CustomField>
    <fullName>Size_Range__c</fullName>
    <label>Size Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>below 10000</fullName>
            </value>
            <value>
                <fullName>10000 - 25000</fullName>
            </value>
            <value>
                <fullName>25000 - 50000</fullName>
            </value>
            <value>
                <fullName>50000 - 100000</fullName>
            </value>
            <value>
                <fullName>Above 1 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit Bundles</relationshipLabel>
    <relationshipName>Unit_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RemoveUnitFromUnitBundle_Test.cls
@isTest
public class RemoveUnitFromUnitBundle_Test {
    @isTest
    static void reqTestMethod(){
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        User u = new User();
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        INSERT u;

        PermissionSet newPermission = [SELECT Id FROM PermissionSet WHERE Name = 'Object_Permission'];
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = newPermission.Id;
        INSERT psa;

        system.runAs(u){
            Opportunity__c opp = new Opportunity__c();
            opp.Name = 'TestOpp';
            opp.Close_Date__c = system.today() + 7;
            opp.Stage__c = 'In Progress'; 
            insert opp;
            
            Unit__c unit = new Unit__c();
            unit.Building_Type__c = 'RCC';
            unit.Ceiling_Side_Height__c = 10;
            unit.Ceiling_Side_Height_UOM__c = 'Feet';
            unit.Ceiling_Center_Height__c = 12;
            unit.Ceiling_Center_Height_UOM__c = 'Feet';
            unit.Flooring_Strength_per_MT__c = '1000';
            unit.Floor_ht_from_ground_level__c = '8';
            unit.Floor_ht_from_ground_level_UOM__c = 'Feet';
            unit.No_of_shutters__c = '4';
            unit.Fire_Noc_available__c = 'Yes';
            unit.Fire_Safety__c = 'Extinguishers';
            unit.Power_available__c = 'Yes';
            unit.Rent_per_uom_Price_per_uom__c = 30;
            unit.Built_up_Area__c = 1200;
            unit.SIDCO_SIPCOT_CAM_or_Addl_Charges__c = 200;
            unit.SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c = 'Feet';
            unit.City__c = 'Zirakpur';
            unit.Canopy_available__c = 'Yes';
            unit.Dock_Leveller__c = 'Yes';
            unit.Advance_Security_Deposit__c = '3000';
            unit.EoT_Crane_Provision__c = 'Yes';
            unit.Office_space_available__c = 'Yes';
            unit.Escalation__c = '8%';
            unit.Size_Range__c = 'below 10000';
            insert unit;
            
            Unit__c unit2 = new Unit__c();
            unit2.Building_Type__c = 'RCC';
            unit2.Ceiling_Side_Height__c = 10;
            unit2.Ceiling_Side_Height_UOM__c = 'Feet';
            unit2.Ceiling_Center_Height__c = 12;
            unit2.Ceiling_Center_Height_UOM__c = 'Feet';
            unit2.Flooring_Strength_per_MT__c = '1000';
            unit2.Floor_ht_from_ground_level__c = '8';
            unit2.Floor_ht_from_ground_level_UOM__c = 'Feet';
            unit2.No_of_shutters__c = '4';
            unit2.Fire_Noc_available__c = 'Yes';
            unit2.Fire_Safety__c = 'Extinguishers';
            unit2.Power_available__c = 'Yes';
            unit2.Rent_per_uom_Price_per_uom__c = 30;
            unit2.Built_up_Area__c = 1200;
            unit2.SIDCO_SIPCOT_CAM_or_Addl_Charges__c = 200;
            unit2.SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c = 'Feet';
            unit2.City__c = 'Zirakpur';
            unit2.Canopy_available__c = 'Yes';
            unit2.Dock_Leveller__c = 'Yes';
            unit2.Advance_Security_Deposit__c = '3000';
            unit2.EoT_Crane_Provision__c = 'Yes';
            unit2.Office_space_available__c = 'Yes';
            unit2.Escalation__c = '8%';
            unit.Size_Range__c = 'below 10000';
            insert unit2;
            
            Shortlisted_Unit__c shortListedUnit = new Shortlisted_Unit__c(
                Unit__c = unit.id
            );
            insert shortListedUnit;
            Shortlisted_Unit__c shortListedUnit2 = new Shortlisted_Unit__c(
                Unit__c = unit2.id
            );
            insert shortListedUnit2;
            
            Unit_Bundle__c unitBundle = new Unit_Bundle__c(
                Name = 'Test Unit Bundle',
               // Opportunity__c = opp.Id,
                Linked_Unit__c = JSON.serialize(new List<String>{shortListedUnit.Id})
            );
            system.debug('unitBundle.Linked_Unit__c --> '+unitBundle.Linked_Unit__c);
            insert unitBundle;
            
            List<RemoveUnitFromUnitBundle.Request> reqs = new List<RemoveUnitFromUnitBundle.Request>();
            RemoveUnitFromUnitBundle.Request req = new RemoveUnitFromUnitBundle.Request();
            req.shortUnitID = shortListedUnit2.id;
            req.unitBundleObj = unitBundle;
            reqs.add(req);
            
            Test.startTest();
            RemoveUnitFromUnitBundle.execute(reqs);
            Test.stopTest();
        }
    }
}