force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Deferred_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deferred_Reason__c</fullName>
    <label>Deferred Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarkSiteVisitDeferred.cls
/**
 * @description This class is used to mark site visit record as deferred using opportunity Id
 */
public without sharing class MarkSiteVisitDeferred {

    /**
     * @description This class is used to mark site visit record as deferred using opportunity Id
     * @param requestLst
     */
    @InvocableMethod(label='Mark Site Visit Deferred' description='Mark Site Visit Deferred')
    public static void execute(List<Request> requestLst){	
        List<Site_Visit__c> siteVisitListUpdated = new List<Site_Visit__c>();
        Set<String> opportunityIds = new Set<String>();
        for(Request req : requestLst){ 
            if(!String.isBlank(req.opportunityId)){
                opportunityIds.add(req.opportunityId);
            }
        }
        
        String numString = String.join(opportunityIds, '\',\'');
        String status = 'Scheduled';
        
        String siteVisitQuery = 'SELECT Id, Deferred_Reason__c, Status__c FROM Site_Visit__c';      
        if(!opportunityIds.isEmpty()){
            siteVisitQuery = siteVisitQuery + ' WHERE Opportunity__c IN (\''+ String.escapeSingleQuotes(numString) +'\') AND Status__c = \'' + String.escapeSingleQuotes(status) + +'\'';
        }else{
            siteVisitQuery = siteVisitQuery + ' WHERE Status__c = \'' + String.escapeSingleQuotes(status) + +'\'';
        }
        
        List<Site_Visit__c> siteVisitList = database.query(siteVisitQuery);
        
        if(!siteVisitList.isEmpty()){
            for(Site_Visit__c siteVisit: siteVisitList){
                siteVisit.Status__c = 'Deferred';
                siteVisit.Deferred_Reason__c = 'Rescheduled';
                siteVisitListUpdated.add(siteVisit);
            }
        }
        
        if(!siteVisitListUpdated.isEmpty()){
            Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Site_Visit__c;
            Boolean thisUserMayUpdate = drSObj.isUpdateable();
            SObjectAccessDecision securityDecision = Security.stripInaccessible(
                                                        AccessType.UPDATABLE,  siteVisitListUpdated);

            if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
                update securityDecision.getRecords();
            }
        }
    }
    
    /**
     * @description This is request wrapper
     */
    public class Request{
        @InvocableVariable(label = 'Opportunity Id' description = 'Record Id of Opportunity' required = false)
        public String opportunityId;
    }
}