force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <label>Current Stage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Previous_Stage__c.field-meta.xml
<CustomField>
    <fullName>Previous_Stage__c</fullName>
    <label>Previous Stage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Service Required</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityHandler.cls
/* 
     *@description       : Whenever the deal breaks in the path, we should know in which stage it was breaked
	  @author            : 
	  @last modified on  : 29/04/2025
      
*/
public class OpportunityHandler {
    
    /*
     @description  Used to Update the Current Stage name
		@param oppList - use to get  list oppList
			@param oppList - use to get  list oldMap
		
     */
    public static void StageUpdated(List<Opportunity__c> oppList,Map<Id,Opportunity__c> oldMap){
        
        Map<String, String> stagePicklistLabels = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Opportunity__c.Stage__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry picklistEntry : picklistValues) {
            stagePicklistLabels.put(picklistEntry.getValue(), picklistEntry.getLabel());
        }
        
        for (Opportunity__c opp : oppList) {
            Opportunity__c oldOpp = oldMap.get(opp.Id);
            
            if (opp.Stage__c != oldOpp.Stage__c) {
                opp.Previous_Stage__c = stagePicklistLabels.get(oldOpp.Stage__c);
                opp.Current_Stage__c = stagePicklistLabels.get(opp.Stage__c);
            }
        }
    }
    /*
     @description  Used to insert the Current Stage name
        @param oppList - use to get  list oppList
     */
    public static void stageInsert(List<Opportunity__c> oppList) {
    for (Opportunity__c opp : oppList) {
        opp.Current_Stage__c = 'Qualified';
    }
    
}
    @AuraEnabled(cacheable=true)
  public static Opportunity__c getOpportunity(Id opportunityId) {
    return [SELECT Id, Property_Type__c FROM Opportunity__c WHERE Id = :opportunityId LIMIT 1];
}
}