force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Area__c</fullName>
    <label>Project Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Area_UOM__c.field-meta.xml
<CustomField>
    <fullName>Project_Area_UOM__c</fullName>
    <label>Project Area UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sq.Ft.</fullName>
            </value>
            <value>
                <fullName>Sq.Meter</fullName>
            </value>
            <value>
                <fullName>Acres</fullName>
            </value>
            <value>
                <fullName>Guntha</fullName>
            </value>
            <value>
                <fullName>Bigha</fullName>
            </value>
            <value>
                <fullName>Sq. Yards</fullName>
            </value>
            <value>
                <fullName>Hectares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetObjectName_Test.cls
@istest
public class GetObjectName_Test {
	@isTest
    static void reqTestMethod(){
        Project__c project = new Project__c();
        project.Name = 'TestProject';
        project.Project_Area__c = 10000; 
        project.Project_Area_UOM__c = 'Sq.Meter';
        insert project;
	
        GetObjectName.Request req = new GetObjectName.Request();
        req.recordId = project.Id;
        Test.startTest();
        GetObjectName.getObject(project.Id);
        GetObjectName.execute(new List<GetObjectName.Request>{req});
        System.assertEquals('Project__c', GetObjectName.getObject(project.Id),'mesg');
        Test.stopTest();
    }
}