force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Google_Coordinates_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Coordinates_Link__c</fullName>
    <label>Google Coordinates Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/getLatitideandLongitudeOnUnitController.cls
public class getLatitideandLongitudeOnUnitController {
    
    @Auraenabled(cacheable=true)
    public static Boolean getUnits(String recordId) {
        // Strip fields that are not readable
        Boolean locationExit = false;
        if(recordId != null && recordId != '')
        {
            
            SObjectAccessDecision decision = Security.stripInaccessible(
                AccessType.READABLE,
                [SELECT Id, Google_Coordinates_Link__c,Unit_Location__Latitude__s,Unit_Location__Longitude__s
                 FROM Unit__c 
                 WHERE Id =: recordId]);
            if(!(decision.getRecords()).isEmpty()) {
                List<Unit__c> unitList = (List<Unit__c>) decision.getRecords();
                Unit__c unit = unitList[0];
                if((unit.Google_Coordinates_Link__c !='' && unit.Google_Coordinates_Link__c != null)|| unit.Unit_Location__Latitude__s != null)
                {
                    locationExit = true;
                }
            }
        }
        
        return locationExit;
        
        
        
    }
    
}