force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Chargeable_Area__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <label>Date Available</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_Range__c.field-meta.xml
<CustomField>
    <fullName>Size_Range__c</fullName>
    <label>Size Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>below 10000</fullName>
            </value>
            <value>
                <fullName>10000 - 25000</fullName>
            </value>
            <value>
                <fullName>25000 - 50000</fullName>
            </value>
            <value>
                <fullName>50000 - 100000</fullName>
            </value>
            <value>
                <fullName>Above 1 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Available for lease</fullName>
                <isActive>false</isActive>
                <label>Available for lease</label>
            </value>
            <value>
                <fullName>Available for sales</fullName>
                <isActive>false</isActive>
                <label>Available for sales</label>
            </value>
            <value>
                <fullName>Available for sales/lease</fullName>
                <isActive>false</isActive>
                <label>Available for sales/lease</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>On lease</fullName>
                <isActive>false</isActive>
                <label>On lease</label>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
                <isActive>false</isActive>
                <label>Shortlisted</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Land.recordType-meta.xml
<RecordType>
    <fullName>Land</fullName>
    <active>true</active>
    <label>Land</label>
</RecordType>

force-app/main/default/classes/PropertyRenewalNotification_Test.cls
@isTest
public class PropertyRenewalNotification_Test {
 @istest 
    public static void mainmethod(){
           Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        User u = new User();
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test1@gmail.comProject';
        u.CommunityNickname = 'test';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        INSERT u;
        
         Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get(System.Label.Person_Account_RecordType_Name)
            .getRecordTypeId();
        Account accountObject = new Account();
        accountObject.FirstName = 'test';
        accountObject.LastName = 'Account';
        accountObject.BillingCountry = 'India';
        accountObject.PersonBirthdate = System.today();
        accountObject.Phone = '455546565';
        accountObject.RecordTypeId = PersonRecId;
        accountObject.PersonEmail = 'test.project@gmail.com';
        insert accountObject;
 		 
        Unit__c unitData = new Unit__c();
        unitData.Name = 'Unit 1';
        unitData.Type_of_Unit__c = 'Land';
        unitData.City__c = 'City1';
        unitData.Country__c = 'Country1';
        unitData.Postal_Code__c = '12345';
        unitData.Chargeable_Area__c = 1500;
        unitData.State__c = 'State1';
        unitData.Street__c = 'Street1';
        unitData.Unit_Status__c = 'Available';
        unitData.Date_Available__c =system.today().addDays(30);
        unitData.Unit_Location__Latitude__s = 30.7333;
        unitData.Unit_Location__Longitude__s = 76.7794;
        unitData.Budget__c = '2.5 lakh to 5 lakh';
        unitData.OwnerId = u.Id;
        unitData.Size_Range__c = 'below 10000';

        Test.startTest();
        insert unitData;
        PropertyRenewalNotification ba= new PropertyRenewalNotification();
        Id jobid= Database.executeBatch(ba);
        PropertyRenewalNotification scheduler = new PropertyRenewalNotification();
		scheduler.execute(null);
        Test.stopTest();
       
    }
}