force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Street__c +&apos; &apos;+ City__c  +&apos; &apos;+ State__c +&apos; &apos;+ Country__c +&apos; &apos;+ Postal_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Category__c.field-meta.xml
<CustomField>
    <fullName>Unit_Category__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Available for lease</fullName>
                <isActive>false</isActive>
                <label>Available for lease</label>
            </value>
            <value>
                <fullName>Available for sales</fullName>
                <isActive>false</isActive>
                <label>Available for sales</label>
            </value>
            <value>
                <fullName>Available for sales/lease</fullName>
                <isActive>false</isActive>
                <label>Available for sales/lease</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>On lease</fullName>
                <isActive>false</isActive>
                <label>On lease</label>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
                <isActive>false</isActive>
                <label>Shortlisted</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnitController.cls
public without sharing class UnitController {
    
    @AuraEnabled
    public static List<Unit__c> searchUnits(String City,Decimal Latitude, Decimal Longitude){
        system.debug('Latitude'+Latitude);
       // Latitude = Latitude.setScale(5);
       // Longitude = Longitude.setScale(5);
       // system.debug('Longitude'+Longitude);
       system.debug('City'+City);
        if(String.isNotBlank(City)){
            List<Unit__c> unitList = [SELECT Name,Unit_Status__c,Type_of_Unit__c,
                                      Unit_Category__c,State__c,
                                      City__c,Street__c,Country__c,
                                      Postal_Code__c,Unit_Location__Longitude__s,
                                      Unit_Location__Latitude__s,Address__c
                                      FROM Unit__c
                                      WHERE City__c LIKE :'%'+City OR
                                      City__c =: City OR
                                      City__c LIKE :City+'%'
                                      /*AND Unit_Location__Latitude__s =: Latitude 
                                      AND Unit_Location__Longitude__s  =: Longitude*/];
           
            if(!unitList.isEmpty()){
                system.debug('unitList'+unitList);
                return unitList;
            }
        }
        
        return null;
        
    }
    
     @AuraEnabled(cacheable=true)
    public static List<ContentVersion> getRelatedCVs(String recordId,String documentType){
        
        if(String.isNotBlank(recordId) && String.isNotBlank(documentType)){
            List<ContentVersion> cvList = [SELECT id
                                          FROM ContentVersion
                                          WHERE FirstPublishLocationId = :recordId];
            if(!cvList.isEmpty()){
                return cvList;
            }
        }
        
        return null;
        
    }

}