force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Chargeable_Area__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <formula>Point_of_Contact__r.PersonMobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <label>Date Available</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/EoT_Crane_Provision__c.field-meta.xml
<CustomField>
    <fullName>EoT_Crane_Provision__c</fullName>
    <label>EoT Crane Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_Range__c.field-meta.xml
<CustomField>
    <fullName>Size_Range__c</fullName>
    <label>Size Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>below 10000</fullName>
            </value>
            <value>
                <fullName>10000 - 25000</fullName>
            </value>
            <value>
                <fullName>25000 - 50000</fullName>
            </value>
            <value>
                <fullName>50000 - 100000</fullName>
            </value>
            <value>
                <fullName>Above 1 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Category__c.field-meta.xml
<CustomField>
    <fullName>Unit_Category__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <displayFormat>UN-{0000}</displayFormat>
    <label>Unit Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Available for lease</fullName>
                <isActive>false</isActive>
                <label>Available for lease</label>
            </value>
            <value>
                <fullName>Available for sales</fullName>
                <isActive>false</isActive>
                <label>Available for sales</label>
            </value>
            <value>
                <fullName>Available for sales/lease</fullName>
                <isActive>false</isActive>
                <label>Available for sales/lease</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>On lease</fullName>
                <isActive>false</isActive>
                <label>On lease</label>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
                <isActive>false</isActive>
                <label>Shortlisted</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Shed.recordType-meta.xml
<RecordType>
    <fullName>Shed</fullName>
    <active>true</active>
    <label>Shed</label>
</RecordType>

force-app/main/default/classes/GetUnitControllerTest.cls
@isTest
public class GetUnitControllerTest {
    
    @testSetup
    static void setup() {
        List<Unit__c> units = new List<Unit__c>();
        
        Unit__c unitData = new Unit__c();
        unitData.Type_of_Unit__c = 'Shed';
        unitData.City__c = 'City1';
        unitData.Country__c = 'Country1';
        unitData.Postal_Code__c = '12345';
        unitData.Chargeable_Area__c = 1500;
        unitData.Saleable_Area__c = 1500;
        unitData.State__c = 'State1';
        unitData.Street__c = 'Street1';
        unitData.Unit_Status__c = 'Available';
        unitData.Unit_Location__Latitude__s = 30.7333;
        unitData.Unit_Location__Longitude__s = 76.7794;
        unitData.Budget__c = '2.5 lakh to 5 lakh';
        unitData.Size_Range__c = '10000 - 25000';
        unitData.Unit_Category__c = 'SIPCOT';
        unitData.EoT_Crane_Provision__c = 'Yes';
        unitData.Date_Available__c = Date.newInstance(2025, 4, 22);
        
        units.add(unitData);
        
        if(!units.isEmpty()){
            insert units;  
        }
    }

    @isTest
    static void testGetFilteredUnits2() {
        
        Unit__c unit = [
            SELECT Id, Type_of_Unit__c, City__c, Country__c,
                   Unit_Category__c, EoT_Crane_Provision__c,
                   Postal_Code__c, Chargeable_Area__c,
                   State__c, Unit_Status__c,
                   Unit_Location__Latitude__s,
                   Unit_Location__Longitude__s,
                   Budget__c, Name
            FROM Unit__c
            LIMIT 1
        ];
        
        unit.Budget__c = '2.5 lakh to 5 lakh';
        unit.Type_of_Unit__c = 'Shed';
        unit.Chargeable_Area__c = 0;
        unit.Unit_Category__c = 'SIPCOT';
        unit.EoT_Crane_Provision__c ='Yes';
        
        update unit;
        
        Test.startTest();
        
        String selectedBudgetType = unit.Budget__c;
        String typeOfUnit = unit.Type_of_Unit__c;
        String unitCategory = unit.Unit_Category__c;
        String eotCrane = unit.EoT_Crane_Provision__c;
        
        double maxArea = unit.Chargeable_Area__c;
        double minArea = unit.Chargeable_Area__c;
        
        Decimal radius = 10;
        Decimal longitude = 76.7794;
        Decimal latitude = 30.7333;
        
        List<Object> interestedLocations = new List<Object>{
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 30.0,
                    'Longitude' => 76.0
                }
            },
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 31.0,
                    'Longitude' => 77.0
                }
            }
        };
        
        GetUnitController.getInterestedLocationsUnit(
            selectedBudgetType,
            typeOfUnit,
            unitCategory,
            eotCrane,
            maxArea,
            minArea,
            latitude,
            longitude,
            radius,
            interestedLocations
        );

        Test.stopTest();
    }

    @isTest
    static void testGetFilteredUnits3() {
        
        Unit__c unit = [
            SELECT Id, Type_of_Unit__c, City__c, Country__c,
                   Postal_Code__c, Chargeable_Area__c,
                   State__c, Unit_Status__c,
                   Unit_Location__Latitude__s,
                   Unit_Location__Longitude__s,
                   Budget__c, Name,
                   Unit_Category__c,
                   EoT_Crane_Provision__c
            FROM Unit__c
            LIMIT 1
        ];
        
        unit.Budget__c = null;
        unit.Type_of_Unit__c = null;
        unit.Chargeable_Area__c = 0;
        unit.Unit_Category__c = 'SIPCOT';
        unit.EoT_Crane_Provision__c ='Yes';
        
        update unit;
        
        Test.startTest();
        
        String selectedBudgetType = unit.Budget__c;
        String typeOfUnit = unit.Type_of_Unit__c;
        String unitCategory = unit.Unit_Category__c;
        String eotCrane = unit.EoT_Crane_Provision__c;
        
        double maxArea = unit.Chargeable_Area__c;
        double minArea = unit.Chargeable_Area__c;
        
        Decimal radius = 10;
        Decimal longitude = 76.7794;
        Decimal latitude = 30.7333;
        
        List<Object> interestedLocations = new List<Object>{
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 30.0,
                    'Longitude' => 76.0
                }
            },
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 31.0,
                    'Longitude' => 77.0
                }
            }
        };
        
        GetUnitController.getInterestedLocationsUnit(
            selectedBudgetType,
            typeOfUnit,
            unitCategory,
            eotCrane,
            maxArea,
            minArea,
            latitude,
            longitude,
            radius,
            interestedLocations
        );

        Test.stopTest();
    }

    @isTest
    static void testGetFilteredUnits4() {
        
        Unit__c unit = [
            SELECT Id, Type_of_Unit__c, City__c, Country__c,
                   Postal_Code__c, Chargeable_Area__c,
                   State__c, Unit_Status__c,
                   Unit_Location__Latitude__s,
                   Unit_Location__Longitude__s,
                   Budget__c, Name,
                   Unit_Category__c,
                   EoT_Crane_Provision__c
            FROM Unit__c
            LIMIT 1
        ];
        
        unit.Budget__c = '';
        unit.Type_of_Unit__c = '';
        unit.Chargeable_Area__c = 0;
        unit.Unit_Category__c = 'SIPCOT';
        unit.EoT_Crane_Provision__c ='Yes';
        
        update unit;
        
        Test.startTest();
        
        String selectedBudgetType = unit.Budget__c;
        String typeOfUnit = unit.Type_of_Unit__c;
        String unitCategory = unit.Unit_Category__c;
        String eotCrane = unit.EoT_Crane_Provision__c;
        
        double maxArea = unit.Chargeable_Area__c;
        double minArea = unit.Chargeable_Area__c;
        
        Decimal radius = 10;
        Decimal longitude = 76.7794;
        Decimal latitude = 30.7333;
        
        List<Object> interestedLocations = new List<Object>{
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 30.0,
                    'Longitude' => 76.0
                }
            },
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 31.0,
                    'Longitude' => 77.0
                }
            }
        };
        
        GetUnitController.getInterestedLocationsUnit(
            selectedBudgetType,
            typeOfUnit,
            unitCategory,
            eotCrane,
            maxArea,
            minArea,
            latitude,
            longitude,
            radius,
            interestedLocations
        );

        Test.stopTest();
    }

    @isTest
    static void testGetFilteredUnits5() {
        
        Unit__c unit = [
            SELECT Id, Type_of_Unit__c, City__c, Country__c,
                   Postal_Code__c, Chargeable_Area__c,
                   State__c, Unit_Status__c,
                   Unit_Location__Latitude__s,
                   Unit_Location__Longitude__s,
                   Budget__c, Name,
                   Unit_Category__c,
                   EoT_Crane_Provision__c
            FROM Unit__c
            LIMIT 1
        ];
        
        unit.Budget__c = '';
        unit.Type_of_Unit__c = 'Shed';
        unit.Chargeable_Area__c = 0;
        unit.Unit_Category__c = 'SIPCOT';
        unit.EoT_Crane_Provision__c ='Yes';
        
        update unit;
        
        Test.startTest();
        
        String selectedBudgetType = unit.Budget__c;
        String typeOfUnit = unit.Type_of_Unit__c;
        String unitCategory = unit.Unit_Category__c;
        String eotCrane = unit.EoT_Crane_Provision__c;
        
        double maxArea = unit.Chargeable_Area__c;
        double minArea = unit.Chargeable_Area__c;
        
        Decimal radius = 10;
        Decimal longitude = 76.7794;
        Decimal latitude = 30.7333;
        
        List<Object> interestedLocations = new List<Object>{
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 30.0,
                    'Longitude' => 76.0
                }
            },
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 31.0,
                    'Longitude' => 77.0
                }
            }
        };
        
        GetUnitController.getInterestedLocationsUnit(
            selectedBudgetType,
            typeOfUnit,
            unitCategory,
            eotCrane,
            maxArea,
            minArea,
            latitude,
            longitude,
            radius,
            interestedLocations
        );

        Test.stopTest();
    }

    @isTest
    static void testGetFilteredUnits6() {
        
        Unit__c unit = [
            SELECT Id, Type_of_Unit__c, City__c, Country__c,
                   Postal_Code__c, Chargeable_Area__c,
                   State__c, Unit_Status__c,
                   Unit_Location__Latitude__s,
                   Unit_Location__Longitude__s,
                   Budget__c, Name,
                   Unit_Category__c,
                   EoT_Crane_Provision__c
            FROM Unit__c
            LIMIT 1
        ];
        
        unit.Budget__c = '2.5 lakh to 5 lakh';
        unit.Type_of_Unit__c = 'Shed';
        unit.Chargeable_Area__c = 100;
        unit.Unit_Category__c = 'SIPCOT';
        unit.EoT_Crane_Provision__c ='Yes';
        
        update unit;
        
        Test.startTest();
        
        String selectedBudgetType = unit.Budget__c;
        String typeOfUnit = unit.Type_of_Unit__c;
        String unitCategory = unit.Unit_Category__c;
        String eotCrane = unit.EoT_Crane_Provision__c;
        
        double maxArea = unit.Chargeable_Area__c;
        double minArea = unit.Chargeable_Area__c;
        
        Decimal radius = 10;
        Decimal longitude = 76.7794;
        Decimal latitude = 30.7333;
        
        List<Object> interestedLocations = new List<Object>{
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 30.0,
                    'Longitude' => 76.0
                }
            },
            new Map<String, Object>{
                'location' => new Map<String, Object>{
                    'Latitude' => 31.0,
                    'Longitude' => 77.0
                }
            }
        };
        
        GetUnitController.getInterestedLocationsUnit(
            selectedBudgetType,
            typeOfUnit,
            unitCategory,
            eotCrane,
            maxArea,
            minArea,
            latitude,
            longitude,
            radius,
            interestedLocations
        );

        Test.stopTest();
    }

    @isTest
    static void getDataByUnitNumber() {
        
        List<Unit__c> units = new List<Unit__c>();
        
        Unit__c unitData = new Unit__c();
        unitData.Name = 'Test Unit';
        unitData.Date_Available__c = Date.newInstance(2025, 4, 22);
        unitData.Budget__c = '2.5 lakh to 5 lakh';
        unitData.Saleable_Area__c = 1200;
        unitData.Type_of_Unit__c = 'Shed';
        unitData.Unit_Status__c = 'Available';
        unitData.Size_Range__c = '10000 - 25000';
        
        units.add(unitData);
        insert unitData;
        
        Unit__c unit = [
            Select Id, Unit_Status__c, Contact_Number__c,
                   Name, Date_Available__c, Budget__c,
                   Saleable_Area__c, Type_of_Unit__c,
                   Unit_Number__c
            From Unit__c
            Where Id = :unitData.Id
        ];
       
        Test.startTest();
        
        List<Unit__c> result = GetUnitController.getDataByUnitNumber(
            unit.Unit_Number__c,
            unit.Name,
            unit.Type_of_Unit__c
        );
        
        Test.stopTest();
    }
    
    @isTest
    static void getUnitsByCrane() {
        
        List<Unit__c> units = new List<Unit__c>();
        
        Unit__c unitData = new Unit__c();
        unitData.Name = 'Test Unit';
        unitData.Date_Available__c = Date.newInstance(2025, 4, 22);
        unitData.Budget__c = '2.5 lakh to 5 lakh';
        unitData.Saleable_Area__c = 1200;
        unitData.Type_of_Unit__c = 'Shed';
        unitData.Unit_Status__c = 'Available';
        unitData.Size_Range__c = '10000 - 25000';
        unitData.Unit_Category__c ='SIPCOT';
        unitData.EoT_Crane_Provision__c = 'Yes';
        
        units.add(unitData);
        insert unitData;        
        
        Unit__c unit = [
            Select Id, Unit_Status__c, EoT_Crane_Provision__c,
                   Unit_Category__c, Contact_Number__c,
                   Name, Date_Available__c, Budget__c,
                   Saleable_Area__c, Type_of_Unit__c,
                   Unit_Number__c
            From Unit__c
            Where Id = :unitData.Id
        ];
       
        Test.startTest();
        
        List<Unit__c> result = GetUnitController.getUnitsByCrane(
            unit.Unit_Category__c,
            unit.EoT_Crane_Provision__c
        );
        
        Test.stopTest();
    }
}