force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sync_Log__c/Data_Sync_Log__c.object-meta.xml
<CustomObject>
    <label>Data Sync Log</label>
    <nameField>
        <displayFormat>DSL - {0000}</displayFormat>
        <label>Data Sync Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sync_Log__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry API</fullName>
            </value>
            <value>
                <fullName>99 Acrs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Sync_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Sync_Log__c/fields/Sync_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sync_Direction__c</fullName>
    <label>Sync Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataSyncService.cls
/**
 * @description This class is used as wrapper for logging api response in system
 */
@NamespaceAccessible
public with sharing class DataSyncService {

    public Data_Sync_Log__c dataSyncLog;
    public List<Data_Sync_Log__c> dataSyncLogList;
	
    /**
     * @description Constructor that initializes object
     */
    @NamespaceAccessible
    public DataSyncService(){
        dataSyncLog = new Data_Sync_Log__c();
    }
	
    /**
     * @description it inserts Data_Sync_Log__c records
     * @param apiRequest
     * @param eventType
     * @param syncDirection
     */
    @NamespaceAccessible
    public void initialize(String apiRequest, String eventType, String syncDirection){    
        
        dataSyncLog.API_Request__c = apiRequest;
        dataSyncLog.Event_Type__c = eventType;
        dataSyncLog.Sync_Direction__c = syncDirection;
        dataSyncLog.Status__c = System.Label.Data_Sync_Inprogress_Status;

        Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Data_Sync_Log__c;
        Boolean thisUserMayUpdate = drSObj.isCreateable();
        SObjectAccessDecision securityDecision = Security.stripInaccessible(
                                                    AccessType.CREATABLE, new List<Data_Sync_Log__c>{dataSyncLog});

        if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
            dataSyncLogList = (List<Data_Sync_Log__c>) securityDecision.getRecords();
            insert dataSyncLogList;

            dataSyncLog.Id = dataSyncLogList[0].Id;
        }
    }
	 
    /**
     * @description it updates status as success with api response
     * @param apiResponse
     */
    @NamespaceAccessible
    public void success(String apiResponse){    
        
        dataSyncLog.Status__c = System.Label.Data_Sync_Success_Status;
        dataSyncLog.API_Response__c = apiResponse;

        Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Data_Sync_Log__c;
        Boolean thisUserMayUpdate = drSObj.isUpdateable();
        SObjectAccessDecision securityDecision = Security.stripInaccessible(
                                                    AccessType.UPDATABLE, new List<Data_Sync_Log__c>{dataSyncLog});

        if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
            update securityDecision.getRecords();
        }
    }
	
     /**
     * @description it updates status as error with api response
     * @param apiResponse
     */
    @NamespaceAccessible
    public void error(String apiResponse){    
        
        dataSyncLog.Status__c = System.Label.Data_Sync_Failed_Status;
        dataSyncLog.API_Response__c = apiResponse;

       /* Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Booking__c;
        Boolean thisUserMayUpdate = drSObj.isUpdateable();
        SObjectAccessDecision securityDecision = Security.stripInaccessible(
                                                    AccessType.UPDATABLE, new List<Data_Sync_Log__c>{dataSyncLog});

        if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
            update securityDecision.getRecords();
        }*/
    }
}