force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <label>Booking Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Booking_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Line_Item__c/fields/Landlord__c.field-meta.xml
<CustomField>
    <fullName>Landlord__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Landlord</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Booking_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Line_Item__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Booking_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateBooking.cls
/**
* @description This class is used to create related data required for booking at the time of booking creation
*/
public without sharing class CreateBooking {
    
    /**
    * @description This is an invocable method used to create related data required for booking at the time of booking creation
    * @param requestLst
    */
    @InvocableMethod(label='Create Booking' description='Create Booking Related Records')
    public static void execute(List<Request> requestLst) {
        List<Booking_Line_Item__c> bookingLineItemList = new List<Booking_Line_Item__c>();
        Set<Id> shortListIds = new Set<Id>();
        
        for(Request req: requestLst) {
            if(!String.isBlank(req.bookingId)) {
             /*   if(!String.isBlank(req.bookingLineItem)) {
                    List<Booking_Line_Item__c> bookingLineItems = (List<Booking_Line_Item__c>) JSON.deserialize(
                        req.bookingLineItem,
                        List<Booking_Line_Item__c>.class
                    );
                    
                    if(!bookingLineItems.isEmpty()) {
                        for (Booking_Line_Item__c bookingLineItem : bookingLineItems) {
                            bookingLineItem.Booking__c = req.bookingId;
                            bookingLineItemList.add(bookingLineItem);
                        }
                    }
                }*/
                
                if(!String.isBlank(req.shorListUnits)) {
                    for(String shorListUnit: (List<String>) JSON.deserialize(req.shorListUnits, List<String>.class)) {
                        shortListIds.add(shorListUnit);
                    }
                }
            }
        }
        
        
        if(!shortListIds.isEmpty()) {
            List<Shortlisted_Unit__c> shorListedUnitList = new List<Shortlisted_Unit__c>();
            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.READABLE,
                                                                        [SELECT Id, Name, Unit__c, Unit__r.Project__c, Status__c,
                                                                         Unit__r.Point_of_Contact__c,
                                                                         Unit__r.Name
                                                                         FROM Shortlisted_Unit__c
                                                                         WHERE Id In: shortListIds]);
            
             
            
            if(!(decision.getRecords()).isEmpty()) {
                for(Shortlisted_Unit__c shorListedUnit: (List<Shortlisted_Unit__c>) decision.getRecords()) {
                    shorListedUnit.Status__c = System.Label.Unit_Status_In_Progress;
                    shorListedUnitList.add(shorListedUnit);
                    
                    Booking_Line_Item__c bookingLineItem = New Booking_Line_Item__c();
                    bookingLineItem.Unit__c = shorListedUnit.Unit__c;
                    bookingLineItem.Booking__c = requestLst[0].bookingId;
                    bookingLineItem.Name = shorListedUnit.Unit__r.Name;
                    bookingLineItem.Landlord__c = shorListedUnit.Unit__r.Point_of_Contact__c;
                    bookingLineItemList.add(bookingLineItem);
                }
            }
            
            if(!bookingLineItemList.isEmpty()) {
            Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Booking_Line_Item__c;
            Boolean thisUserMayUpdate = drSObj.isCreateable();
            SObjectAccessDecision securityDecision = Security.stripInaccessible(
                AccessType.CREATABLE, bookingLineItemList);
            
            if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate) {
                insert securityDecision.getRecords();
            }
        }
        
            if(!shorListedUnitList.isEmpty()) {
                Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Shortlisted_Unit__c;
                Boolean thisUserMayUpdate = drSObj.isUpdateable();
                SObjectAccessDecision securityDecision = Security.stripInaccessible(
                    AccessType.UPDATABLE,  shorListedUnitList);
                
                if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate) {
                    update securityDecision.getRecords();
                }
            }
        }
    }
    
    /**
    * @description This is request wrapper
    */
    public class Request {
        
        @InvocableVariable(label = 'bookingId' description = 'Id of Booking' required = true)
        public String bookingId;
        
        @InvocableVariable(label = 'ShorList Units' description = 'ShorList Units JSON' required = true)
        public String shorListUnits;
        
    }
}