force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Line_Item__c/Booking_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Booking Line Item</label>
    <nameField>
        <label>Booking Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Booking_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Line_Item__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Booking_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <formula>TEXT( Unit__r.Unit_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_Range__c.field-meta.xml
<CustomField>
    <fullName>Size_Range__c</fullName>
    <label>Size Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>below 10000</fullName>
            </value>
            <value>
                <fullName>10000 - 25000</fullName>
            </value>
            <value>
                <fullName>25000 - 50000</fullName>
            </value>
            <value>
                <fullName>50000 - 100000</fullName>
            </value>
            <value>
                <fullName>Above 1 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Available for lease</fullName>
                <isActive>false</isActive>
                <label>Available for lease</label>
            </value>
            <value>
                <fullName>Available for sales</fullName>
                <isActive>false</isActive>
                <label>Available for sales</label>
            </value>
            <value>
                <fullName>Available for sales/lease</fullName>
                <isActive>false</isActive>
                <label>Available for sales/lease</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>On lease</fullName>
                <isActive>false</isActive>
                <label>On lease</label>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
                <isActive>false</isActive>
                <label>Shortlisted</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/Land.recordType-meta.xml
<RecordType>
    <fullName>Land</fullName>
    <active>true</active>
    <label>Land</label>
</RecordType>

force-app/main/default/classes/CreateBooking_test.cls
@isTest public class CreateBooking_test {
    
    @isTest static void CreateBookingTestMethod(){
        
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        User u = new User();
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        INSERT u;
        PermissionSet newPermission = [SELECT Id FROM PermissionSet WHERE Name = 'Object_Permission'];
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = newPermission.Id;
        INSERT psa;
        system.runAs(u){
            
            Id personAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(System.Label.Person_Account_RecordType_Name).getRecordTypeId();
            
            Account acc = new Account();
            acc.RecordTypeID = personAccountId;
            acc.FirstName = 'Test';
            acc.LastName = 'User';
            acc.PersonEmail = 'TestUser@gmail.com';
            acc.PersonMobilePhone = '65464453435';
            insert acc;
            Project__c project = new Project__c();
            project.Name = 'Test Project';
            insert project;
            Opportunity opp = new Opportunity();
            opp.Name='test';
            opp.AccountId=acc.id;
            opp.CloseDate=system.today();
            opp.StageName='Prospecting';
            insert opp;
            
            Unit__c unit = new Unit__c ();
            //unit.Name = 'Unit 1';
            unit.Type_of_Unit__c = 'Land';
            unit.City__c = 'City1';
            unit.Country__c = 'Country1';
            unit.Postal_Code__c = '12345';
            unit.Saleable_Area__c = 1500;
            unit.State__c = 'State1';
            unit.Street__c = 'Street1';
            unit.Unit_Status__c = 'Available';
            unit.Unit_Location__Latitude__s = 30.7333;
            unit.Unit_Location__Longitude__s = 76.7794;
            unit.Budget__c = '2.5 lakh to 5 lakh';
            unit.Point_of_Contact__c = acc.Id;
            unit.Size_Range__c = 'below 10000';
            insert unit;
            
            List<Shortlisted_Unit__c> ShortlistedUnitList = new List<Shortlisted_Unit__c>(); 
            Shortlisted_Unit__c shortList = new Shortlisted_Unit__c();
            shortList.Status__c='Shortlisted';
           // shortList.Opportunity__c=opp.id;
            shortList.Unit__c = Unit.id;
            ShortlistedUnitList.add(shortList);
            try{
                insert shortList;  
            }catch(exception ex){
                
            }
            
            
            List<string> ShortlistedUnitList1 = new List<string>(); 
            ShortlistedUnitList1.add(ShortlistedUnitList[0].id);
            Booking__c booking = new Booking__c();
            booking.name='testbooking';
            
            booking.Booking_Date__c=system.today();
            insert booking;
            List<Booking_Line_Item__c> bookingLineItemList = new List<Booking_Line_Item__c>(); 
            Booking_Line_Item__c bookingLineItem = new Booking_Line_Item__c();
            bookingLineItem.name = 'testing';
            bookingLineItem.Quantity__c=12;
            bookingLineItem.Booking__c=booking.id;
            bookingLineItem.Unit__c=unit.id;
            
            bookingLineItemList.add(bookingLineItem);
            
            
            
            List<CreateBooking.Request> reqlist= new List<CreateBooking.Request>();
            CreateBooking.Request req= new CreateBooking.Request();
            req.bookingId = booking.id;
            req.shorListUnits= JSON.serialize(ShortlistedUnitList1);
            
            reqlist.add(req);
            Test.startTest();
            CreateBooking.execute(reqlist);
            
            Test.stopTest();
        }
    }
    
    
}