force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Payment Reminder</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Registration</fullName>
                <isActive>false</isActive>
                <label>Registration</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_Range__c.field-meta.xml
<CustomField>
    <fullName>Size_Range__c</fullName>
    <label>Size Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>below 10000</fullName>
            </value>
            <value>
                <fullName>10000 - 25000</fullName>
            </value>
            <value>
                <fullName>25000 - 50000</fullName>
            </value>
            <value>
                <fullName>50000 - 100000</fullName>
            </value>
            <value>
                <fullName>Above 1 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit Bundles</relationshipLabel>
    <relationshipName>Unit_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Shortlist by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Unit_UOM__c.field-meta.xml
<CustomField>
    <fullName>Unit_UOM__c</fullName>
    <label>Unit UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SetBookingName_test.cls
@istest 
public class SetBookingName_test {
     @isTest
    static void ReqTestMethod(){
   
        Unit__c unit01 = new Unit__c();
        unit01.Name = 'TestUnit01';
       // unit01.Default_Charge__c = charge.id;
      
        unit01.Carpet_Area__c = 1000;
      //  unit01.Saleable_Area__c = 1000;
       unit01.Unit_UOM__c = 'Feet';
        unit01.Size_Range__c = 'below 10000';
        insert unit01;
        
        Unit__c unit02 = new Unit__c();
        unit02.Name = 'TestUnit02';
     
     
       // unit02.Saleable_Area__c = 1000;
        unit02.Unit_UOM__c = 'Feet';
        unit02.Size_Range__c = 'below 10000';
       // unit02.Preferred_Locations__c = charge01.Id + ';';       
        insert unit02;

   
        
       

        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get('Person Account').getRecordTypeId();
        Account personAcct = new account();
        personAcct.lastName = 'ginny';
        personAcct.RecordTypeId = recordTypeId;
        insert personAcct;

        Opportunity__c opp = new Opportunity__c();
        //opp.Account_Name__c = personAcct.id;
        opp.Name = 'TestOpp';
        opp.Close_Date__c = system.today() + 7;
        opp.Stage__c = 'In Progress'; 
        insert opp;

        Shortlisted_Unit__c shortUnit01 = new Shortlisted_Unit__c();
        shortUnit01.Status__c = 'Booked';
        shortUnit01.Unit__c = unit01.id;
        shortUnit01.Opportunity__c = opp.id;
        insert shortUnit01;

        Shortlisted_Unit__c shortUnit02 = new Shortlisted_Unit__c();
        shortUnit02.Status__c = 'Booked';
        shortUnit02.Unit__c = unit02.id;
        shortUnit02.Opportunity__c = opp.id;
        insert shortUnit02;

       
        Unit_Bundle__c unitBundle = new Unit_Bundle__c();
        //unitBundle.Opportunity__c = opp.Id;
        unitBundle.Name = 'TestUnitBundle';
        unitBundle.Linked_Unit__c = '["' + shortUnit01.id + '","' + shortUnit02.id + '"]';
        insert unitBundle;

      

        Booking__c booking = new Booking__c();
        booking.Booking_Date__c = System.today();
        booking.Related_Opportunity__c = opp.Id;
        insert booking;
    

        List<SetBookingName.Request> reqlist= new List<SetBookingName.Request>();
        SetBookingName.Request req= new SetBookingName.Request();
        req.bookingId = booking.id;
         
        reqlist.add(req);
        Test.startTest();
        SetBookingName.execute(reqlist);
        //SetBookingName.generateFieldValueMap(fieldValues,'Name');
        Test.stopTest();
    }
    
         @isTest
    static void ReqTestMethod2(){
       Map<String, Object> fieldValues = new Map<String, Object>();
        
        Unit__c unit01 = new Unit__c();
        unit01.Name = 'TestUnit01';
     
        unit01.Carpet_Area__c = 1000;
       
        unit01.Unit_UOM__c = 'Feet';
        unit01.Size_Range__c = 'below 10000';
        insert unit01;
        
        Unit__c unit02 = new Unit__c();
        unit02.Name = 'TestUnit02';
       
        unit02.Unit_UOM__c = 'Feet';
        unit02.Size_Range__c = 'below 10000';
             
        insert unit02;

       

        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                  .get('Person Account').getRecordTypeId();

        Account personAcct = new account();
        personAcct.lastName = 'ginny';
        personAcct.RecordTypeId = recordTypeId;
        insert personAcct;

        Opportunity__c opp = new Opportunity__c();
        //opp.Account_Name__c = personAcct.id;
        opp.Name = 'TestOpp';
        opp.Close_Date__c = system.today() + 7;
        opp.Stage__c = 'In Progress'; 
        insert opp;
        Shortlisted_Unit__c shortUnit01 = new Shortlisted_Unit__c();
        shortUnit01.Status__c = 'Booked';
        shortUnit01.Unit__c = unit01.id;
       // shortUnit01.Opportunity__c = opp.id;
        insert shortUnit01;

        Shortlisted_Unit__c shortUnit02 = new Shortlisted_Unit__c();
        shortUnit02.Status__c = 'Booked';
        shortUnit02.Unit__c = unit02.id;
        //shortUnit02.Opportunity__c = opp.id;
        insert shortUnit02;

       

        Unit_Bundle__c unitBundle = new Unit_Bundle__c();
      //  unitBundle.Opportunity__c = opp.Id;
        unitBundle.Name = 'TestUnitBundle';
       
        unitBundle.Linked_Unit__c = '["' + shortUnit01.id + '","' + shortUnit02.id + '"]';
        insert unitBundle;

         Booking__c booking = new Booking__c();
        booking.Booking_Date__c = System.today();
        //booking.Related_Opportunity1__c = opp.Id;
        insert booking;
        
       List<SetBookingName.Request> reqlist= new List<SetBookingName.Request>();
        SetBookingName.Request req= new SetBookingName.Request();
        req.bookingId = booking.id;
         
        reqlist.add(req);
        Test.startTest();
        SetBookingName.execute(reqlist);
        SetBookingName.generateFieldValueMap(fieldValues,'');
        Test.stopTest();
    }    
}