force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Invoice_Date__c</fullName>
    <label>Booking Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Landlord_name__c.field-meta.xml
<CustomField>
    <fullName>Landlord_name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Landlord name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Landlord name</relationshipLabel>
    <relationshipName>Booking1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/reminder__c.field-meta.xml
<CustomField>
    <fullName>reminder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>reminder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Reminder_Week__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Week__c</fullName>
    <formula>IF(
TODAY() - Booking_Invoice_Date__c &lt;= 7,
&quot;First Week&quot;,
IF(
TODAY() - Booking_Invoice_Date__c &lt;= 14,
&quot;Second Week&quot;,
IF(
TODAY() - Booking_Invoice_Date__c &lt;= 21,
&quot;Third Week&quot;,
IF(
TODAY() - Booking_Invoice_Date__c &lt;= 28,
&quot;Fourth Week&quot;,
&quot;Beyond Fourth Week&quot;
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reminder Week</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking (Tenant)</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Reminder__mdt/Invoice_Reminder__mdt.object-meta.xml
<CustomObject>
    <label>Invoice Reminder</label>
    <pluralLabel>Invoice Reminders</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice_Reminder__mdt/fields/First_Reminder__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder__c</fullName>
    <label>First Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Reminder__mdt/fields/Fourth_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Reminder__c</fullName>
    <label>Fourth Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Reminder__mdt/fields/Second_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder__c</fullName>
    <label>Second Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Reminder__mdt/fields/Third_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Third_Reminder__c</fullName>
    <label>Third Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SendRemindersBatch.cls
global class SendRemindersBatch implements Database.Batchable<SObject>, Schedulable {
    public integer firstReminderDate;
    public integer secondReminderDate;
    public integer thirdReminderDate;
    public integer fourthReminderDate;
    public List<Invoice_Reminder__mdt> invoiceReminder ;
   
    global Database.QueryLocator start(Database.BatchableContext BC) {
         invoiceReminder = [
            SELECT Id, First_Reminder__c, Fourth_Reminder__c, 
                   Third_Reminder__c, Second_Reminder__c 
            FROM Invoice_Reminder__mdt LIMIT 1
        ];

        if (!invoiceReminder.isEmpty()) {
            firstReminderDate = Integer.valueOf(invoiceReminder[0].First_Reminder__c);
            secondReminderDate = Integer.valueOf(invoiceReminder[0].Second_Reminder__c);
            thirdReminderDate = Integer.valueOf(invoiceReminder[0].Third_Reminder__c);
            fourthReminderDate = Integer.valueOf(invoiceReminder[0].Fourth_Reminder__c);
        }
        
 
         String query = 'SELECT Id, ' + 
                       'Name, ' +
           				'Landlord_name__r.PersonEmail ,' +
                       'Next_Reminder_Date__c, ' +
                       'Reminder_Week__c, ' +
           				'Booking_Invoice_Date__c ,' +
                       'CreatedDate, ' +
           				' Owner.Email,'+
                        ' Tenant__c, '+
                       ' Landlord_name__c '+
                      ' FROM Booking__c ' +
             		      'WHERE reminder__c = false ' +
               'AND Landlord_name__r.PersonEmail != null '+
             	'AND Owner.Email != null';
        return Database.getQueryLocator(query);

    }

    global void execute(Database.BatchableContext BC, List<Booking__c> scope) {
        system.debug('scope'+scope);
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        List<EmailTemplate> emailTemp = [SELECT Id, Name, Subject, Body FROM EmailTemplate WHERE DeveloperName = 'Transaction_Assignment'];
        List<Booking__c> updateBooking = new List<Booking__c>();

           if (!scope.isEmpty()) {
            for (Booking__c booking : scope) {
                system.debug('scope'+scope);
             if (booking.Tenant__c != null  && booking.Landlord_name__c != null) {
                   Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemp[0].Id, null, booking.Id);
                        mail.setToAddresses(new List<String>{booking.Landlord_name__r.PersonEmail});
                        mail.setCcAddresses(new List<String>{booking.Owner.Email});
                        mail.setSaveAsActivity(false);
                        mails.add(mail);
                	 Date nextReminderDate;
                 if (booking.Reminder_Week__c == 'First Week') {
                     if (booking.Next_Reminder_Date__c == null) {
                        system.debug('First'+firstReminderDate);
                     	 nextReminderDate = booking.Booking_Invoice_Date__c.addDays(firstReminderDate);
                     }}	
                    else if (booking.Reminder_Week__c == 'Second Week') {
                       if (booking.Next_Reminder_Date__c != null) {
                            nextReminderDate = booking.Next_Reminder_Date__c.addDays(secondReminderDate);
                        }
                        system.debug('secondReminderDate'+booking.Next_Reminder_Date__c);
                    } else if (booking.Reminder_Week__c == 'Third Week') {
                        if (booking.Next_Reminder_Date__c != null) {
                       		nextReminderDate =  booking.Next_Reminder_Date__c.addDays(thirdReminderDate);
            			 	system.debug('ThirdReminderDate'+booking.Next_Reminder_Date__c);
                        }} else {
                       if (booking.Next_Reminder_Date__c != null) {
                       nextReminderDate =  booking.Next_Reminder_Date__c.addDays(fourthReminderDate);
            
                         system.debug('fourthReminderDate'+booking.Next_Reminder_Date__c);
                       } }
                     booking.Next_Reminder_Date__c = nextReminderDate;
                    	updateBooking.add(booking);
					 
                }
            }

            if (!mails.isEmpty()) {
             Messaging.sendEmail(mails);
            }

            if (!updateBooking.isEmpty()) {
                update updateBooking;
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        // Any post-batch cleanup or processing can be done here
    }

    global void execute(SchedulableContext sc) {
        SendRemindersBatch batch = new SendRemindersBatch();
        Database.executeBatch(batch);
    }
}