force-app/main/default/objects/Account/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Budget_Range1__c.field-meta.xml
<CustomField>
    <fullName>Budget_Range1__c</fullName>
    <label>Budget_Range</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Source__c</fullName>
    <label>Enquiry Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Nature_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Purchase__c</fullName>
    <label>Nature of Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Purchase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Reason_for_Closed__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Closed__c</fullName>
    <label>Reason for Closed</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Test Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Referral_Name__c.field-meta.xml
<CustomField>
    <fullName>Referral_Name__c</fullName>
    <label>Referral Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Size_in_sqfts__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqfts__c</fullName>
    <label>Size (in sqft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Types_of_F_W__c.field-meta.xml
<CustomField>
    <fullName>Types_of_F_W__c</fullName>
    <label>Types of F&amp;W</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Unit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Factory</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/recordTypes/Landlord.recordType-meta.xml
<RecordType>
    <fullName>Landlord</fullName>
    <active>true</active>
    <label>Landlord</label>
</RecordType>

force-app/main/default/objects/Enquiry__c/recordTypes/Tenant.recordType-meta.xml
<RecordType>
    <fullName>Tenant</fullName>
    <active>true</active>
    <label>Tenant</label>
</RecordType>

force-app/main/default/objects/Interested_Locations__c/Interested_Locations__c.object-meta.xml
<CustomObject>
    <label>Interested Location</label>
    <nameField>
        <label>Interested Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interested Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interested_Locations__c/fields/Interested_Location_Range__c.field-meta.xml
<CustomField>
    <fullName>Interested_Location_Range__c</fullName>
    <label>Interested Location Range</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interested_Locations__c/fields/Related_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Related_Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Interested Locations</relationshipLabel>
    <relationshipName>Interested_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Source__c</fullName>
    <label>Enquiry Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nature_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Purchase__c</fullName>
    <label>Nature of Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Purchase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size (in sqft.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Budget_Range1__c.field-meta.xml
<CustomField>
    <fullName>Budget_Range1__c</fullName>
    <label>Budget_Range</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Enquiry__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Source__c</fullName>
    <label>Enquiry Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Service Required</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Referral_Name__c.field-meta.xml
<CustomField>
    <fullName>Referral_Name__c</fullName>
    <label>Referral Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Size_in_sqfts__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqfts__c</fullName>
    <label>Size (in sqfts.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnquiryObjectTest.cls
/* 
*@description       : When the Enquiry Status is 'Closed' and the Reason is 'Qualified', 
an Opportunity should be created with the Stage set to 'Qualified Test class
@author            : Ruban
@last modified on  : 29/04/2025

*/

@isTest
public class EnquiryObjectTest {
    @testsetup
    static void setupData(){
        	 RecordType rc = [SELECT Id, Name, DeveloperName, SObjectType 
FROM RecordType 
WHERE SObjectType = 'Account' 
AND DeveloperName = 'PersonAccount'];
		 Account acc = new Account(LastName='Test Name',RecordTypeId = rc.Id);
        insert acc;
        
        RecordType landRT = [
            SELECT Id FROM RecordType
            WHERE SObjectType = 'Enquiry__c' AND Name = 'Tenant'
            LIMIT 1
        ];
        Enquiry__c enq1=new Enquiry__c(
            Name = 'Test Enquiry 1',
                Status__c = 'Closed',
                Reason_for_Closed__c = 'Qualified',
                 Mobile__c = '9876543210',
            	Contact_Person__c = acc.Id,
                RecordTypeId = landRT.Id,
            Size_in_sqft__c  = '10000 - 25000',
            Size_in_sqfts__c = 15000,
             Type_of_Unit__c = 'Land',
            Types_of_F_W__c = ''
        );
        Insert enq1;
        
          RecordType rt = [SELECT Id, Name FROM RecordType 
                 WHERE DeveloperName = 'Tenant' 
                 AND SObjectType = 'Enquiry__c' 
                 LIMIT 1];
        Enquiry__c enquiry = new Enquiry__c(
            Name = 'Test Enquiry',
            Email__c = 'testuser@example.com',
            Type_of_Unit__c = 'Land', // match with unit
            Status__c ='Closed',
            Mobile__c ='1111100076',
            Reason_for_Closed__c = 'Qualified',
            Contact_Person__c = acc.Id,
            RecordTypeId =rt.Id,
			Size_in_sqft__c  = '10000 - 25000',//Added on 11-11-2025
            Size_in_sqfts__c = 15000//size range Added on 11-11-2025
        );
        insert enquiry;
         Interested_Locations__c interestedLoc = new Interested_Locations__c(
            Address__Latitude__s = 12.8728,     // near Urapakkam
            Address__Longitude__s = 80.0823,
            Related_Enquiry__c = enquiry.Id,
            Interested_Location_Range__c = 5
        );
        insert interestedLoc;
        
    }
    @isTest
    static void testOpportunityCreation(){
        List<Enquiry__c> enquiries = [SELECT Id, Name, Type_of_Unit__c, Status__c, Reason_for_Closed__c, RecordTypeId,Contact_Person__c,Budget_Range1__c,Nature_of_Purchase__c,
                                      Size_in_sqft__c, Enquiry_Source__c, Enquiry_Sub_Source__c,Customer_Name__c, Referral_Name__c, Size_in_sqfts__c FROM Enquiry__c];
        Interested_Locations__c interestedLoc1 = new Interested_Locations__c(
            Address__Latitude__s = 12.8728,     // near Urapakkam
            Address__Longitude__s = 80.0823,
            Related_Enquiry__c = enquiries[0].Id,
            Interested_Location_Range__c = 5
        );
        insert interestedLoc1;
        Test.startTest();
        EnquiryObject.createOpportunities(enquiries);
        
        Test.stopTest();
        
        List<Opportunity__c> createdOpportunity = [
            SELECT Id, Name, Enquiry__c, Stage__c, Record_Type__c, Account_Name__c 
            FROM Opportunity__c
        ];
        EnquiryObject.getOpportunity(createdOpportunity[0].Enquiry__c);
        for (Opportunity__c opp : createdOpportunity) {
            if (opp.Record_Type__c == 'Tenant') {
                System.assertEquals('Tenant', opp.Record_Type__c, 'Record type should be Tenant');
            } else if (opp.Record_Type__c == 'Landlord') {
                System.assertEquals('landlord', opp.Record_Type__c, 'Record type should be landlord');
            }
		}
        
    }
    @isTest
    static void testCreateOpportunities() {
        List<Enquiry__c> enquiryList = new List<Enquiry__c>{
            new Enquiry__c(
                Name = 'Test Enquiry 1',
                Status__c = 'Closed',
                Reason_for_Closed__c = 'Qualified',
                 Mobile__c = '9876543210',
               // Email__c = 'test1@gmail.com', //Added on 11-11-2025
                RecordTypeId = Schema.SObjectType.Enquiry__c.getRecordTypeInfosByName().get('Tenant').getRecordTypeId(),
                Size_in_sqft__c  = '10000 - 25000',
            Size_in_sqfts__c = 15000,
             Type_of_Unit__c = 'Land',
            Types_of_F_W__c = ''
            )
                };
                    
                    insert enquiryList;
        
        Test.startTest();
        EnquiryObject.createOpportunities(enquiryList);
        Test.stopTest();
        
      /*  Opportunity__c createdOpportunity = [
            SELECT Id, Name, Enquiry__c, Stage__c, Record_Type__c, Account_Name__c,Property_Type__c
            FROM Opportunity__c Where Stage__c = 'Qualified'
            LIMIT 1
        ];
        
        
        // Check that Stage__c is 'Qualified'
        System.assertEquals('Qualified', createdOpportunity.Stage__c, 'Stage should be Qualified');*/
    }
}