force-app/main/default/objects/Site_Visit_Inspection_Checklist__mdt/Site_Visit_Inspection_Checklist__mdt.object-meta.xml
<CustomObject>
    <label>Site Visit Inspection Checklist</label>
    <pluralLabel>Site Visit Inspection Checklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/Site_Visit_Inspection_Checklist__mdt/fields/Datatype__c.field-meta.xml
<CustomField>
    <fullName>Datatype__c</fullName>
    <label>Datatype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integer</fullName>
                <default>true</default>
                <label>Integer</label>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit_Inspection_Checklist__mdt/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No..</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit_Inspection_Checklist__mdt/fields/Text_Label__c.field-meta.xml
<CustomField>
    <fullName>Text_Label__c</fullName>
    <label>Text Label</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GetSiteVisitInspectionChecklistMetadata.cls
public class GetSiteVisitInspectionChecklistMetadata {
    @AuraEnabled(cacheable = true)
    public static List<Object> execute(){
        List<Object>returnList = New List<Object>();
        List<Site_Visit_Inspection_Checklist__mdt> inspectionCheckList = [SELECT Id,Label,MasterLabel,Sequence_No__c,
                                                                                  Text_Label__c,Datatype__c
                                                                                  FROM Site_Visit_Inspection_Checklist__mdt	 
                                                                                  ORDER BY Sequence_No__c ASC];
        
        system.debug('inspectionCheckList'+inspectionCheckList);
        if(!inspectionCheckList.IsEmpty()){
            for(Site_Visit_Inspection_Checklist__mdt mdt :inspectionCheckList){
                returnList.add(mdt);
            }
        }
        return returnList;
    }
    
    
}