force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <formula>DATEVALUE( Visit_Date_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CalendarController.cls
public class CalendarController {
	@AuraEnabled(cacheable=true)
    public static List<Task> getTasks() {
        return [SELECT Id, Subject, ActivityDate, Status, Priority, WhatId, What.Name, ReminderDateTime, 
                       IsReminderSet, OwnerId,Owner.Name, Assigned_By__c,Assigned_By__r.Name, Due_Date_Time__c
                       FROM Task WHERE Due_Date_Time__c != null];
    }

    @AuraEnabled(cacheable=true)
    public static List<Site_Visit__c> getSiteVisits() {
        return [SELECT Id, Name, Visit_Date__c FROM Site_Visit__c WHERE Visit_Date__c != NULL];
    }
}