force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <formula>DATEVALUE( Visit_Date_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SiteVisitReminderBatch.cls
global class SiteVisitReminderBatch implements Database.Batchable<SObject>, Schedulable {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
    
        return Database.getQueryLocator([
            SELECT Name, Id, Account__c, Account__r.PersonEmail, Visit_Date__c 
            FROM Site_Visit__c
            WHERE Account__r.PersonEmail != null 
            AND Visit_Date__c != null 
            AND (Visit_Date__c = :System.today() OR Visit_Date__c = :System.today().addDays(1))
        ]);
    }
    global void execute(Database.BatchableContext BC, List<Site_Visit__c> scope) {
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        List<EmailTemplate> emailTemp = [Select Id, Subject, Description, HtmlValue, DeveloperName, Body from EmailTemplate 
                                         where DeveloperName =: 'Template_for_Informing_about_Scheduling_Site_Visit_to_Tenant' limit 1];
       
        if(!scope.isEmpty()){
            for(Site_Visit__c siteV:scope){
                system.debug('siteV==>'+siteV);
                   if(siteV.Visit_Date__c !=null){
                    Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemp[0].Id, null, siteV.Id);
                    mail.setToAddresses(new List<String>{siteV.Account__r.PersonEmail});
                    mail.setSaveAsActivity(true);
                    mails.add(mail);  
                      }
                
            }
            if(!mails.isEmpty()){
               // Messaging.sendEmail(mails);
            }
        }
    }
    global void finish(Database.BatchableContext BC) {
        
    }
    global void execute(SchedulableContext sc) {
        
        SiteVisitReminderBatch batch = new SiteVisitReminderBatch();
        Database.executeBatch(batch);
    }
}