force-app/main/default/objects/Opportunity/fields/Proposal_Json__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Json__c</fullName>
    <label>Proposal Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Share_Location__c.field-meta.xml
<CustomField>
    <fullName>Share_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Share Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Landlord_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Landlord Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Landlord_Name__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Landlord Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BTSproposalControllerTest.cls
/**
* @File Name : GpsCameraImageController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : May 22, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 21, 2025 |   | Initial Version
**/
@isTest
public class BTSproposalControllerTest {
    
    @isTest
    static void testBTSProposalController() {
        // Step 1: Create a test Opportunity__c with JSON in Proposal_Json__c
        Opportunity__c opp = new Opportunity__c(
            Name = 'Test Opportunity',
            Proposal_Json__c = '[{"Id":"001","Name":"Test Bundle","UnitData":[{"Data":{"Name":"Unit1"},"selectedContentVersionID":["12345"]}]}]',
            Share_Location__c = true,
            Landlord_Name__c = true,
            Landlord_Mobile__c = true
        );
        insert opp;


        // Step 3: Set parameters for the controller
        Test.setCurrentPage(Page.BTSProposal); // Replace with actual VF page name
        ApexPages.currentPage().getParameters().put('id', opp.Id);
        ApexPages.currentPage().getParameters().put('selectedFields', 'Landlord_Name__c,Landlord_Mobile__c');

        // Step 4: Instantiate controller
        Test.startTest();
        BTSProposalController controller = new BTSProposalController();
        Test.stopTest();

        
        
        // Step 5: Assertions
        System.assertNotEquals(null, controller.unitBundles, 'UnitBundles should not be null');
        System.assert(controller.googleMapLinkShare, 'Google Map link share should be true');
        System.assert(controller.landlordName, 'Landlord name should be true');
        System.assert(controller.landlordMobile, 'Landlord mobile should be true');
        System.assert(controller.showField('Landlord_Name__c'), 'Field should be shown');
        System.assert(!controller.showField('NonExistentField'), 'Field should not be shown');
        
        for (BTSProposalController.UnitBundle bundle : controller.unitBundles) {
            String testUrl = bundle.Url;
            System.debug('Generated URL: ' + testUrl);
            System.assert(testUrl.contains('?id='), 'URL should include ID query param');
        }
    }
}