force-app/main/default/objects/Employee_Time_Sheet__c/Employee_Time_Sheet__c.object-meta.xml
<CustomObject>
    <label>Employee Time Sheet</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Time Sheets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Time_Sheet__c/fields/Time_In__c.field-meta.xml
<CustomField>
    <fullName>Time_In__c</fullName>
    <label>Time In</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Employee_Time_Sheet__c/fields/Time_Out__c.field-meta.xml
<CustomField>
    <fullName>Time_Out__c</fullName>
    <label>Time Out</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Employee_Time_Sheet__c/fields/Total_Working_Hours1__c.field-meta.xml
<CustomField>
    <fullName>Total_Working_Hours1__c</fullName>
    <label>Total Working Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Time_Sheet__c/fields/Total_Working_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Working_Hours__c</fullName>
    <label>Total Working Hours</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeTimeSheetsTriggerHandlerTest.cls
@isTest
public class EmployeeTimeSheetsTriggerHandlerTest {
	@isTest
    static void testCalculateTotalWorkingHours_AllCases() {
        Employee_Time_Sheet__c validRecord = new Employee_Time_Sheet__c(
            Time_In__c = Time.newInstance(10, 0, 0, 0),
            Time_Out__c = Time.newInstance(18, 30, 0, 0)
        );
        Employee_Time_Sheet__c missingTimeIn = new Employee_Time_Sheet__c(
            Time_In__c = null,
            Time_Out__c = Time.newInstance(12, 0, 0, 0)
        );
        Employee_Time_Sheet__c exceptionRecord = new Employee_Time_Sheet__c(
            Time_In__c = Time.newInstance(1, 0, 0, 0),
            Time_Out__c = Time.newInstance(2, 0, 0, 0)
        );
        Test.startTest();
        EmployeeTimeSheetsTriggerHandler.calculateTotalWorkingHours(
            new List<Employee_Time_Sheet__c>{validRecord, missingTimeIn, exceptionRecord}
        );
        Test.stopTest();
        System.assertEquals('8 Hrs 30 Min', validRecord.Total_Working_Hours__c);
        System.assertEquals(8.5, validRecord.Total_Working_Hours1__c);

        System.assertEquals(null, missingTimeIn.Total_Working_Hours__c);
        System.assertEquals(null, missingTimeIn.Total_Working_Hours1__c);

        /*System.assertEquals(null, exceptionRecord.Total_Working_Hours__c);
        System.assertEquals(null, exceptionRecord.Total_Working_Hours1__c);*/
    }  
}