force-app/main/default/objects/BuildeOpedia_Configuration__mdt/BuildeOpedia_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>BuildeOpedia Configuration</label>
    <pluralLabel>BuildeOpedia Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Created_From__c.field-meta.xml
<CustomField>
    <fullName>Created_From__c</fullName>
    <label>Created From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Created_From</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Reason_for_Closed__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Closed__c</fullName>
    <label>Reason for Closed</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Test Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Site_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Date__c</fullName>
    <label>Site Visit Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Site_Visit_Location__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Visit Location</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Enquiry__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Create_Event__c.field-meta.xml
<CustomField>
    <fullName>Create_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Created_From__c.field-meta.xml
<CustomField>
    <fullName>Created_From__c</fullName>
    <label>Created From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Created_From</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Deferred_Reason__c.field-meta.xml
<CustomField>
    <fullName>Deferred_Reason__c</fullName>
    <label>Deferred Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Office</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EnquiryService.cls
/**
* @description This class is a helper class to create enquiry from api 
*/
public without sharing class EnquiryService {
    
    /**
* @description This method is used to create enquiry
* @param request
* @return enquiry response
*/
    public static EnquiryRestService.EnquiryResponse createEnquiry(EnquiryRestService.EnquiryRequest request) {
        Id personAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get(System.Label.Person_Account_RecordType_Name)
            .getRecordTypeId();
        EnquiryRestService.EnquiryResponse response = new EnquiryRestService.EnquiryResponse();
        
        Map<String, String> validateCheck = validateValues(
            request.contactMap
        );
        
        if (validateCheck.isEmpty() && validateCheck.size() <= 0) {
            List<Account> accountList = new List<Account>();
            List<Enquiry__c> enquiryList = new List<Enquiry__c>();
            Set<String> emailSet = new Set<String>();
            Set<String> phoneSet = new Set<String>();
            
            emailSet.add(request.contactMap.get('PersonEmail'));
            phoneSet.add(request.contactMap.get('PersonMobilePhone'));
            
            Account accountObject = new Account();
            for (String contctString : request.contactMap.keySet()) {
                accountObject.put(contctString, request.contactMap.get(contctString));
            }
            accountObject.RecordTypeID = personAccountId;
            accountList.add(accountObject);
            
            Enquiry__c enquiryObject = new Enquiry__c();
            for (String enqString : request.enquiryMap.keySet()) {
               System.debug('enqString'+enqString);
                if(enqString.contains('intentType'))
                {
                    system.debug('Yes');
                    String enquiryRecordTypeName = String.Valueof(request.enquiryMap.get(enqString));
                    Id enquiryRecordTypeId = Schema.SObjectType.Enquiry__c.getRecordTypeInfosByName()
                        .get(enquiryRecordTypeName)
                        .getRecordTypeId();
                    System.debug('enquiryRecordTypeId'+enquiryRecordTypeId);
                    enquiryObject.put('RecordTypeId', enquiryRecordTypeId);
                }
                else
                {
                    String objectName = 'Enquiry__c';
                    String fieldName = enqString;
                    
                    Schema.DisplayType enquiryField = Schema.getGlobalDescribe()
                        .get(objectName)
                        .getDescribe()
                        .fields
                        .getMap()
                        .get(fieldName)
                        .getDescribe()
                        .getType();
                    system.debug('(request.enquiryMap.get(enqString))'+(request.enquiryMap.get(enqString)));
                    System.debug('string.valueof(enquiryField)'+string.valueof(enquiryField) );
                    if (string.valueof(enquiryField) == 'DATETIME') {
                        enquiryObject.put(enqString, Datetime.valueof(request.enquiryMap.get(enqString)));
                    } else if (string.valueof(enquiryField) == 'DATE') {
                        enquiryObject.put(enqString, Date.valueof(request.enquiryMap.get(enqString)));
                    }
                    else if(string.valueof(enquiryField) == 'INTEGER')
                    {
                         enquiryObject.put(enqString, Integer.valueof(request.enquiryMap.get(enqString)));
                    }
                     else if(string.valueof(enquiryField) == 'DOUBLE')
                    {
                         enquiryObject.put(enqString, decimal.valueof(request.enquiryMap.get(enqString)));
                    }
                    
                    
                    else {
                        enquiryObject.put(enqString, request.enquiryMap.get(enqString));
                    }
                }
            }
            
            enquiryObject.Mobile__c = request.contactMap.get('PersonMobilePhone');
            enquiryObject.Email__c = request.contactMap.get('PersonEmail');
            
            Boolean gotError = false;
            if (String.isBlank(enquiryObject.Id)) {
                enquiryList.add(enquiryObject);
                
                List<Enquiry__c> enquiryToBeInserted = new List<Enquiry__c>();
                enquiryToBeInserted = EnquiryService.searchAccountAndLinkEnquiry(
                    accountList,
                    enquiryList
                );
                
                if (!enquiryToBeInserted.isEmpty()) {
                    Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Enquiry__c;
                    Boolean thisUserMayUpdate = drSObj.isCreateable();
                    SObjectAccessDecision securityDecision = Security.stripInaccessible(
                        AccessType.CREATABLE,  enquiryToBeInserted);
                    
                    if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
                        Database.DMLOptions dml = new Database.DMLOptions(); 
                        dml.DuplicateRuleHeader.AllowSave = true;
                        
                        for(Enquiry__c enq: (List<Enquiry__c>) securityDecision.getRecords()){
                            Database.SaveResult sr = Database.insert(enq, dml);
                            
                            if(sr.isSuccess() == false){
                                gotError = true;
                                
                                Map<String, String> errorMap = new Map<String, String>();
                                String errorMessage;
                                for(Database.Error err : sr.getErrors()) {
                                    if(!String.isBlank(errorMessage)){
                                        errorMessage = errorMessage + ', '+ err.getMessage();
                                    }else{
                                        errorMessage = err.getMessage();
                                    }
                                }
                                
                                response.status = System.Label.Error_Status_Enquiry_Api;
                                response.errorMessage = errorMap;
                            }
                            
                            if(sr.getId() != null){
                                enquiryObject.Id = sr.getId();
                            }
                        }
                        
                        if(gotError == false){
                            List<Enquiry__c> enquiryListQueried = [SELECT Id, Name,
                                                                   Site_Visit_Location__c,
                                                                   Site_Visit_Date__c,
                                                                   Contact_Person__c
                                                                   FROM Enquiry__c
                                                                   WHERE Id =: enquiryObject.Id
                                                                  ];
                            CheckAndCreateSiteVisit(enquiryListQueried);
                        }
                    }
                }
                
            } else {
                Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Enquiry__c;
                Boolean thisUserMayUpdate = drSObj.isUpdateable();
                SObjectAccessDecision securityDecision = Security.stripInaccessible(
                    AccessType.UPDATABLE,  new List<Enquiry__c>{enquiryObject});
                
                if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
                    update securityDecision.getRecords();
                    
                    CheckAndCreateSiteVisit((List<Enquiry__c>) securityDecision.getRecords());
                }
            }
            
            if(gotError == false){
                response.status = System.Label.Success_Status_Enquiry_Api;
                response.enquiryData = enquiryObject;
            }
        } else {
            response.status = System.Label.Error_Status_Enquiry_Api;
            response.errorMessage = validateCheck;
        }
        
        return response;
    }
    
    /**
* @description This method is used to validate mandatory fields for contact details
* @param contactMap
* @return errorMessageList
*/
    public static Map<String, String> validateValues( Map<String, String> contactMap) {
        Map<String, String> errorMessageList = new Map<String, String>();
        
        FieldSetInfo.FieldSet fieldSets = FieldSetInfo.getFieldSet('','Account','MandatoryFieldsEnquiryApi');
        List<String> fieldlist = new List<String>();
        for(FieldSetInfo.Fields field: fieldSets.Fields){
            if(contactMap.get(field.apiName) == null){
                fieldlist.add(field.label);
            }
        }
        
        if(!fieldlist.isEmpty()){
            errorMessageList.put(System.Label.Mandatory_Field_Message, String.join(fieldlist, ','));
        }
        
        return errorMessageList;
    }
    
    /**
* @description This method is used to check duplicate account and link it with enquiry
* @param accountList
* @param enquiryList
* @return list of enquiry
*/
    public static List<Enquiry__c> searchAccountAndLinkEnquiry(
        List<Account> accountList,
        List<Enquiry__c> enquiryList
    ) {
        List<Enquiry__c> enquiryToBeInserted = new List<Enquiry__c>();
        
        if (!accountList.isEmpty()) {
            List<Account> accountToBeInserted = new List<Account>();
            Map<String, Account> phoneMap = new Map<String, Account>();
            Map<String, Account> emailMap = new Map<String, Account>();
            
            for(Account acc: accountList){
                CheckDuplicate.Request req = new CheckDuplicate.Request();
                req.record = acc;
                
                for(CheckDuplicate.Response res: CheckDuplicate.execute(new List<CheckDuplicate.Request>{ req } )){
                    if(!String.isBlank(res.duplicateRecordId)){
                        acc.Id = res.duplicateRecordId;
                        if (!String.isBlank(acc.PersonMobilePhone)) {
                            phoneMap.put(acc.PersonMobilePhone, acc);
                        }
                        if (!String.isBlank(acc.PersonEmail)) {
                            emailMap.put(acc.PersonEmail, acc);
                        }
                    }else{
                        accountToBeInserted.add(acc);
                    }
                } 
            }
            
            if(!accountToBeInserted.isEmpty()){
                Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Account;
                Boolean thisUserMayUpdate = drSObj.isCreateable();
               
                
                if(thisUserMayUpdate){
                     SObjectAccessDecision securityDecision = Security.stripInaccessible(
                    AccessType.CREATABLE,  accountToBeInserted);
                    insert securityDecision.getRecords();
                    if(!(securityDecision.getRecords()).isEmpty()){
                    for (Account acc : (List<Account>) securityDecision.getRecords()) {  //(List<Account>) securityDecision.getRecords()
                        if (!String.isBlank(acc.PersonMobilePhone)) {
                            phoneMap.put(acc.PersonMobilePhone, acc);
                        }
                        if (!String.isBlank(acc.PersonEmail)) {
                            emailMap.put(acc.PersonEmail, acc);
                        }
                    }
                }
                }
            }
            
            if (!enquiryList.isEmpty()) {
                for (Enquiry__c enquiry : enquiryList) {
                    if (emailMap.containskey(enquiry.Email__c)) {
                        enquiry.Contact_Person__c = emailMap.get(enquiry.Email__c)?.Id;
                        enquiry.Name = setEnquiryName(emailMap,enquiry.Email__c);
                    }
                    
                    if (enquiry.Contact_Person__c == null || Test.isRunningTest()) {
                        if (phoneMap.containskey(enquiry.Mobile__c)) {
                            enquiry.Contact_Person__c = phoneMap.get(enquiry.Mobile__c)?.Id;
                            enquiry.Name = setEnquiryName(phoneMap,enquiry.Mobile__c);
                        }else if(emailMap.containskey(enquiry.Email__c)){
                            enquiry.Contact_Person__c = phoneMap.get(enquiry.Email__c)?.Id;
                            enquiry.Name = setEnquiryName(phoneMap,enquiry.Email__c);
                        }
                    }
                    
                    enquiry.Created_From__c = System.Label.Created_From_API;
                    enquiry.OwnerId = Test.isRunningTest()?UserInfo.getUserId():BuildeOpedia_Configuration__mdt.getInstance('DefaultEnquiryOwner').value__c;
                    enquiryToBeInserted.add(enquiry);
                }
            }
        }
        return enquiryToBeInserted;
    }
    
    /**
* @description This method is used to set enquiry in a specific format
* @param accountMap
* @param key
* @return String(enquiry name)
*/
    public static String setEnquiryName(Map<String, Account> accountMap, String key){
        String enquiryName;
        
        if(!String.isBlank(accountMap.get(key).Salutation)){
            enquiryName = accountMap.get(key).Salutation;
        }
        
        if(!String.isBlank(accountMap.get(key).FirstName)){
            if(!String.isBlank(enquiryName)){
                enquiryName = enquiryName + ' ' + accountMap.get(key).FirstName;
            }else{
                enquiryName = accountMap.get(key).FirstName;
            }
        }
        
        if(!String.isBlank(enquiryName)){
            enquiryName = enquiryName + ' ' + accountMap.get(key).LastName;
        }else{
            enquiryName = accountMap.get(key).LastName;
        }
        
        return enquiryName;
    }
    
    /**
* @description This method is used to create site visit record with respect to enquiry
* @param enquiryList
*/
    public static void CheckAndCreateSiteVisit( List<Enquiry__c> enquiryList ){
        if(!enquiryList.isEmpty()){
            
            List<Site_Visit__c> siteVisitToBeInserted = new List<Site_Visit__c>();
            Set<Id> siteVisitLocationSet = new Set<Id>();
            
            for(Enquiry__c enq: enquiryList){
                if(enq.Site_Visit_Location__c != null){
                    siteVisitLocationSet.add(enq.Site_Visit_Location__c);
                }
            }
            
            Map<Id,String> siteVisitLocationMap = new Map<Id,String>();
            SObjectAccessDecision decisionBusinessHours = Security.stripInaccessible(
                AccessType.READABLE,
                [SELECT Id, Name
                 FROM BusinessHours 
                 WHERE Id In: siteVisitLocationSet]);
            
            if(!(decisionBusinessHours.getRecords()).isEmpty()) {
                for(BusinessHours bhs: (List<BusinessHours>) decisionBusinessHours.getRecords()){
                    siteVisitLocationMap.put(bhs.Id,bhs.Name);
                }
            }
            
            Set<Id> enquiryIds = new Set<Id>();
            for(Enquiry__c enq: enquiryList){
                if(enq.Site_Visit_Date__c != null){
                    Site_Visit__c siteVisit = new Site_Visit__c();
                    
                    String siteVisitName = enq.Name;
                    
                    if(enq.Site_Visit_Location__c != null){
                        siteVisit.Sales_Office__c = enq.Site_Visit_Location__c;
                        siteVisitName = siteVisitName + '-' + siteVisitLocationMap.get(enq.Site_Visit_Location__c);
                    }
                    
                    siteVisitName = siteVisitName + '-' + enq.Site_Visit_Date__c.format('dd-MM-yyyy HH:mm:ss');
                    
                    siteVisit.Enquiry__c = enq.Id;
                    siteVisit.Account__c = enq.Contact_Person__c;
                    siteVisit.Visit_Date_Time__c = enq.Site_Visit_Date__c;
                    siteVisit.Status__c = 'Scheduled';
                    siteVisit.Created_From__c = System.Label.Created_From_API;
                    siteVisit.Name = siteVisitName;
                    siteVisit.Create_Event__c = true;
                    siteVisitToBeInserted.add(siteVisit);
                    
                    enquiryIds.add(enq.Id);
                }
            }
            
            if(!enquiryIds.isEmpty()){
                List<Site_Visit__c> siteVisitToBeUpdated = new List<Site_Visit__c>();
                SObjectAccessDecision decisionSiteVisit = Security.stripInaccessible(
                    AccessType.READABLE,
                    [ SELECT 
                     Id, 
                     Status__c 
                     FROM Site_Visit__c 
                     WHERE Enquiry__c =: enquiryIds
                     AND Status__c = 'Scheduled']);
                
                if(!(decisionSiteVisit.getRecords()).isEmpty()) {
                    for(Site_Visit__c siteVisit: (List<Site_Visit__c>) decisionSiteVisit.getRecords()){
                        
                        siteVisit.Status__c = 'Deferred';
                        siteVisit.Deferred_Reason__c = 'Rescheduled';
                        siteVisitToBeUpdated.add(siteVisit);
                    }
                }
                
                if(!siteVisitToBeUpdated.isEmpty()){
                    Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Site_Visit__c;
                    Boolean thisUserMayUpdate = drSObj.isUpdateable();
                    SObjectAccessDecision securityDecision = Security.stripInaccessible(
                        AccessType.UPDATABLE,  siteVisitToBeUpdated);
                    
                    if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
                        insert securityDecision.getRecords();
                    }
                }
            }
            
            if(!siteVisitToBeInserted.isEmpty()){
                Schema.DescribeSObjectResult drSObj = Schema.sObjectType.Site_Visit__c;
                Boolean thisUserMayUpdate = drSObj.isCreateable();
                SObjectAccessDecision securityDecision = Security.stripInaccessible(
                    AccessType.CREATABLE,  siteVisitToBeInserted);
                
                if(!(securityDecision.getRecords()).isEmpty() && thisUserMayUpdate){
                    insert securityDecision.getRecords();
                }
            }
        }
    }
public static void CreateRelatedOpportunity(List<Enquiry__c> enquiryList) {
    List<Opportunity__c> oppToInsert = new List<Opportunity__c>();
    
    System.debug('Input Enquiry List: ' + enquiryList);

    for (Enquiry__c enq : enquiryList) {
        System.debug('Checking Enquiry: ' + enq);
        
        if (enq.Status__c == 'Closed' && enq.Reason_for_Closed__c == 'Qualified') {
            Opportunity__c opp = new Opportunity__c();
            opp.Name = enq.Name;
            opp.Stage__c = 'Qualified';
            oppToInsert.add(opp);
            System.debug('Opportunity prepared: ' + opp);
        }
    }
    
    if (!oppToInsert.isEmpty()) {
        insert oppToInsert;
        System.debug('Opportunities inserted: ' + oppToInsert);
    } else {
        System.debug('No Opportunities to insert.');
    }
}

}