force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interested_Locations__c/Interested_Locations__c.object-meta.xml
<CustomObject>
    <label>Interested Location</label>
    <nameField>
        <label>Interested Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interested Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interested_Locations__c/fields/Interested_Location_Range__c.field-meta.xml
<CustomField>
    <fullName>Interested_Location_Range__c</fullName>
    <label>Interested Location Range</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interested_Locations__c/fields/Related_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Related_Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Interested Locations</relationshipLabel>
    <relationshipName>Interested_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LinkInterestedLocationWOpportunity_Test.cls
@isTest
public class LinkInterestedLocationWOpportunity_Test {
	@isTest
    public static void testRun(){
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        
        User u = new User();
        u.FirstName = 'test';
        u.LastName = 'test';
        u.Alias = 'ttest';
        u.Email = 'test@gmail.com';
        u.Username = 'test@gmail.com.stylam202204';
        u.CommunityNickname = 'test';
        u.TimeZoneSidKey = 'America/Los_Angeles';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.ProfileId = pf.Id;
        INSERT u;
        PermissionSet newPermission = [SELECT Id FROM PermissionSet WHERE Name = 'Object_Permission'];
        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = newPermission.Id;
        INSERT psa;
        system.runAs(u){
            
            Enquiry__c enquiry = new Enquiry__c();
            enquiry.Status__c='New';
            enquiry.Mobile__c='7894561234';
            insert enquiry;
            

            Opportunity opp = new Opportunity(
                Name = 'Test Opportunity',
                StageName = 'Prospecting',
                CloseDate = Date.today().addDays(30)
            );
            insert opp;
            
            Interested_Locations__c intLoc = new Interested_Locations__c();
            intLoc.Name = 'Interested_Locations__c';
            intLoc.Related_Enquiry__c = enquiry.Id;
            intLoc.Interested_Location_Range__c = 25;
            insert intLoc;
            
            List<LinkInterestedLocationWithOpportunity.Request> reqList = new List<LinkInterestedLocationWithOpportunity.Request>();
            LinkInterestedLocationWithOpportunity.Request req = new LinkInterestedLocationWithOpportunity.Request();
            req.enquiryId = enquiry.Id;
            req.opportunityId = opp.Id;
            reqList.add(req);
            
            Test.startTest();
            LinkInterestedLocationWithOpportunity.execute(reqList);
            Test.stopTest();
        }
    }
}