force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Enquiry__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Status__c</fullName>
    <formula>TEXT( Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Visit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <formula>DATEVALUE( Visit_Date_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PostInspectionService.cls
public class PostInspectionService {

    @InvocableMethod
    public static void sendReport(List<String> oppIds) {
        Id oppId = oppIds[0];
        Opportunity__c opp = [SELECT Enquiry__c FROM Opportunity__c WHERE Id = :oppId LIMIT 1];

        Enquiry__c enq = [SELECT Name, Email__c FROM Enquiry__c WHERE Id = :opp.Enquiry__c LIMIT 1];

        List<Site_Visit__c> visits = [SELECT Id, Visit_Date__c
                                              FROM Site_Visit__c
                                      WHERE Opportunity__c = :oppId AND Site_Visit_Status__c = 'Completed'AND Visit_Date__c = TODAY];

       /* if(visits.isEmpty()){
            return;
        }*/

        PageReference pdfPage = Page.SiteVisitPDF;
        pdfPage.getParameters().put('oppId', oppId);

        Blob pdfBlob;

        if(Test.isRunningTest()){
            pdfBlob = Blob.valueOf('Test PDF');
        } else {
            pdfBlob = pdfPage.getContent();
        }

        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName('Post_Inspection_Report.pdf');
        attachment.setBody(pdfBlob);

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[]{enq.Email__c});       
        mail.setSubject('Post Inspection Reports -- ' + enq.Name + ' | ' + String.valueOf(visits[0].Visit_Date__c));      

        mail.setPlainTextBody(
            'Dear ' + enq.Name + ',\n\n' +
            'Good day.\n\n' +
            'Please find attached the post-inspection reports dated ' + String.valueOf(visits[0].Visit_Date__c) + '.\n\n' +
            'Kindly review and share your feedback.\n\n' +
            'Regards,\nTeam'
        );

        mail.setFileAttachments(new Messaging.EmailFileAttachment[]{attachment});

        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
    }
}