force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/recordTypes/Landlord.recordType-meta.xml
<RecordType>
    <fullName>Landlord</fullName>
    <active>true</active>
    <label>Landlord</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Share_Location__c.field-meta.xml
<CustomField>
    <fullName>Share_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Share Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Enquiry__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Landlord_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Landlord Mobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Landlord_Name__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Landlord Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Negotiation_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Checklist__c</fullName>
    <label>Negotiation Checklist</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Service Required</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Size_Range__c.field-meta.xml
<CustomField>
    <fullName>Size_Range__c</fullName>
    <label>Size Range</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>below 10000</fullName>
            </value>
            <value>
                <fullName>10000 - 25000</fullName>
            </value>
            <value>
                <fullName>25000 - 50000</fullName>
            </value>
            <value>
                <fullName>50000 - 100000</fullName>
            </value>
            <value>
                <fullName>Above 1 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/recordTypes/BTS.recordType-meta.xml
<RecordType>
    <fullName>BTS</fullName>
    <active>true</active>
    <label>BTS</label>
</RecordType>

force-app/main/default/objects/Unit__c/recordTypes/Land.recordType-meta.xml
<RecordType>
    <fullName>Land</fullName>
    <active>true</active>
    <label>Land</label>
</RecordType>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Negotiation_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Checklist__c</fullName>
    <label>Negotiation Checklist</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit Bundles</relationshipLabel>
    <relationshipName>Unit_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Shortlist by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentGenerationTest.cls
/**
* @File Name : DocumentGenerationTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : May 16, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 16, 2025 |   | Initial Version
**/
@isTest
public class DocumentGenerationTest {
	
    // Create common test data
    static testMethod void testGenerateQuotePdf() {
		 // Create Account
		 RecordType rc = [SELECT Id, Name, DeveloperName, SObjectType 
FROM RecordType 
WHERE SObjectType = 'Account' 
AND DeveloperName = 'PersonAccount'];
		 Account acc = new Account(LastName='Test Name',RecordTypeId = rc.Id);
        insert acc;
	Map<String, Id> rtMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Enquiry__c']) {
            rtMap.put(rt.DeveloperName, rt.Id);
        }
    // Create Enquiry__c with the RecordType
    Enquiry__c enquiry = new Enquiry__c(
        Name = 'Test Enquiry',
        RecordTypeId = rtMap.get('Landlord'),
        Status__c = 'New', 
    	Email__c = 'test@example.com',
        Contact_Person__c = acc.Id,
        Mobile__c='1234567890'
    );
    insert enquiry;

    // Create Opportunity__c
    Opportunity__c opp = new Opportunity__c(
        Name = 'Test Opportunity',
        Property_Type__c = 'Leasing',
        Account_Name__c = acc.Id,
        Enquiry__c = enquiry.Id,
        Share_Location__c = true,
        Landlord_Name__c = true,
        Landlord_Mobile__c = true
    );
    insert opp;
        Unit__c unit = new Unit__c(
            Name = 'Test BTS Unit',
            Type_of_Unit__c = 'BTS',
            Size_Range__c = 'below 10000'
        );
        insert unit;
	String Name = 'Test Negotiation_Checklist__c';
            String Value = 'qwerty';
            Integer SequenceNo = 2;
            String DefaultValue = 'abcd';
    String checklistJSON = JSON.serialize(new List<Object>{
    new Map<String, Object>{
        'Name' => Name,
        'Value' => Value,
        'SequenceNo' => SequenceNo,
        'DefaultValue' => DefaultValue,
        'AdditionalValue' => 'Test',
        'IsMainHeading' => 'true',
        'IsHeading' => 'true',
        'IsSubLabel' => 'true',
        'colSpan' => 2,
        'colSpan2' => 3,
        'sequenceVisible' => 'true',
        'AdditionalVisible' => 'true',
        'Disclaimer' => 'false'
    },
    new Map<String, Object>{
        'Name' => 'Checklist 2',
        'Value' => 'val2',
        'SequenceNo' => 3,
        'DefaultValue' => 'def2',
        'AdditionalValue' => 'Extra',
        'IsMainHeading' => 'false',
        'IsHeading' => 'false',
        'IsSubLabel' => 'true',
        'colSpan' => 1,
        'colSpan2' => 1,
        'sequenceVisible' => 'false',
        'AdditionalVisible' => 'false',
        'Disclaimer' => 'true'
    }
});

    // Create Unit_Bundle__c
    Unit_Bundle__c bundle = new Unit_Bundle__c(
        Name = 'Test Bundle',
        Opportunity__c = opp.Id,
        Negotiation_Checklist__c = checklistJson
       
    );
    insert bundle;
        // Create Shortlisted_Unit__c
        Shortlisted_Unit__c  shortunit = new Shortlisted_Unit__c(

            Opportunity__c = opp.Id,
            Unit_Bundle__c = bundle.Id,
            Unit__c = unit.Id
        );
        insert shortunit;

        Test.startTest();
        Test.setCurrentPage(Page.QuotePdf); // For BTS
        DocumentGeneration gen = new DocumentGeneration();
        gen.GenerateQuotePdf(opp.Id,'LeasingProposal.Pdf');
        Test.stopTest();

       List<ContentVersion> cvs = [SELECT Id, Title FROM ContentVersion WHERE Title LIKE '%Leasing%'];
        System.assert(!cvs.isEmpty(), 'ContentVersion for Land should be inserted');
    }
     @isTest
    static void testGenerateQuotePdf_Land() {
        Opportunity__c opp = new Opportunity__c(
            Name = 'Test Opp Land',
            Property_Type__c = 'Land',
            Share_Location__c = false,
            Landlord_Name__c = false,
            Landlord_Mobile__c = false
        );
        insert opp;

        Unit__c unit = new Unit__c(
            Name = 'Test Unit',
            Type_of_Unit__c = 'BTS',
            Size_Range__c = 'below 10000'
            
        );
        insert unit;

        Shortlisted_Unit__c shortlist = new Shortlisted_Unit__c(
            Opportunity__c = opp.Id,
            Unit__c = unit.Id
        );
        insert shortlist;

        Test.startTest();
        Test.setCurrentPage(Page.LandProposal); // For Land
        new DocumentGeneration().GenerateQuotePdf(opp.Id,'LandProposal.Pdf'); 
        Test.stopTest();

        List<ContentVersion> cvs = [SELECT Id, Title FROM ContentVersion WHERE Title LIKE '%Land%'];
        System.assert(!cvs.isEmpty(), 'ContentVersion for Land should be inserted');
    }
	 @isTest
    static void testGenerateQuotePdf_BTS() {
        Opportunity__c opp = new Opportunity__c(
            Name = 'Test Opp BTS',
            Property_Type__c = 'BTS',
            Share_Location__c = true,
            Landlord_Name__c = true,
            Landlord_Mobile__c = false
        );
        insert opp;

        Unit__c unit = new Unit__c(
            Name = 'Test BTS Unit',
            Type_of_Unit__c = 'BTS',
            Size_Range__c = 'below 10000'
        );
        insert unit;

        Shortlisted_Unit__c shortlist = new Shortlisted_Unit__c(
            Opportunity__c = opp.Id,
            Unit__c = unit.Id
        );
        insert shortlist;

        Test.startTest();
        Test.setCurrentPage(Page.BTSProposal); // For BTS
        new DocumentGeneration().GenerateQuotePdf(opp.Id,'BTSProposal.Pdf'); 
        Test.stopTest();

        List<ContentVersion> cvs = [SELECT Id, Title FROM ContentVersion WHERE Title LIKE '%BTS%'];
        System.assert(!cvs.isEmpty(), 'ContentVersion for BTS should be inserted');
    }
    
    static testMethod void testGenerateNegotiationChecklistPdf() {
        // Create Account
		RecordType rc = [SELECT Id, Name, DeveloperName, SObjectType 
FROM RecordType 
WHERE SObjectType = 'Account' 
AND DeveloperName = 'PersonAccount'];
		 Account acc = new Account(LastName='Test Name',RecordTypeId = rc.Id);
        insert acc;
	Map<String, Id> rtMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Enquiry__c']) {
            rtMap.put(rt.DeveloperName, rt.Id);
        }
    // Create Enquiry__c with the RecordType
    Enquiry__c enquiry = new Enquiry__c(
        Name = 'Test Enquiry',
        RecordTypeId = rtMap.get('Landlord'),
        Status__c = 'New', 
    	Email__c = 'test@example.com',
        Contact_Person__c = acc.Id,
        Mobile__c='1234567890'
    );
    insert enquiry;

    // Create Opportunity__c
    Opportunity__c opp = new Opportunity__c(
        Name = 'Test Opportunity',
        Account_Name__c = acc.Id,
        Enquiry__c = enquiry.Id
    );
    insert opp;
        
	String Name = 'Test Negotiation_Checklist__c';
            String Value = 'qwerty';
            Integer SequenceNo = 2;
            String DefaultValue = 'abcd';
    String checklistJSON = JSON.serialize(new List<Object>{
    new Map<String, Object>{
        'Name' => Name,
        'Value' => Value,
        'SequenceNo' => SequenceNo,
        'DefaultValue' => DefaultValue,
        'AdditionalValue' => 'Test',
        'IsMainHeading' => 'true',
        'IsHeading' => 'true',
        'IsSubLabel' => 'true',
        'colSpan' => 2,
        'colSpan2' => 3,
        'sequenceVisible' => 'true',
        'AdditionalVisible' => 'true',
        'Disclaimer' => 'false'
    },
    new Map<String, Object>{
        'Name' => 'Checklist 2',
        'Value' => 'val2',
        'SequenceNo' => 3,
        'DefaultValue' => 'def2',
        'AdditionalValue' => 'Extra',
        'IsMainHeading' => 'false',
        'IsHeading' => 'false',
        'IsSubLabel' => 'true',
        'colSpan' => 1,
        'colSpan2' => 1,
        'sequenceVisible' => 'false',
        'AdditionalVisible' => 'false',
        'Disclaimer' => 'true'
    }
});

    // Create Unit_Bundle__c
    Unit_Bundle__c bundle = new Unit_Bundle__c(
        Name = 'Test Bundle',
        Opportunity__c = opp.Id,
        Negotiation_Checklist__c = checklistJson
       
    );
    insert bundle;


        Test.startTest();
        DocumentGeneration gen = new DocumentGeneration();
        gen.GenerateNegotiationChecklistPdf(opp.Id, bundle.Id, 'Test');
        Test.stopTest();

        List<ContentVersion> conList = [SELECT Id FROM ContentVersion WHERE Document_Type__c = 'Negotiation Checklist'];
        System.assertEquals(1, conList.size(), 'Negotiation Checklist PDF should be inserted');
    }

    static testMethod void testGenerateSiteVisitQuotePdf() {
         // Create Account
		 RecordType rc = [SELECT Id, Name, DeveloperName, SObjectType 
FROM RecordType 
WHERE SObjectType = 'Account' 
AND DeveloperName = 'PersonAccount'];
		 Account acc = new Account(LastName='Test Name',RecordTypeId = rc.Id);
        insert acc;
	Map<String, Id> rtMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Enquiry__c']) {
            rtMap.put(rt.DeveloperName, rt.Id);
        }
    // Create Enquiry__c with the RecordType
    Enquiry__c enquiry = new Enquiry__c(
        Name = 'Test Enquiry',
        RecordTypeId = rtMap.get('Landlord'),
        Status__c = 'New', 
    	Email__c = 'test@example.com',
        Contact_Person__c = acc.Id,
        Mobile__c='1234567890'
    );
    insert enquiry;

    // Create Opportunity__c
    Opportunity__c opp = new Opportunity__c(
        Name = 'Test Opportunity',
        Account_Name__c = acc.Id,
        Enquiry__c = enquiry.Id
    );
    insert opp;
        
	String Name = 'Test Negotiation_Checklist__c';
            String Value = 'qwerty';
            Integer SequenceNo = 2;
            String DefaultValue = 'abcd';
    String checklistJSON = JSON.serialize(new List<Object>{
    new Map<String, Object>{
        'Name' => Name,
        'Value' => Value,
        'SequenceNo' => SequenceNo,
        'DefaultValue' => DefaultValue,
        'AdditionalValue' => 'Test',
        'IsMainHeading' => 'true',
        'IsHeading' => 'true',
        'IsSubLabel' => 'true',
        'colSpan' => 2,
        'colSpan2' => 3,
        'sequenceVisible' => 'true',
        'AdditionalVisible' => 'true',
        'Disclaimer' => 'false'
    },
    new Map<String, Object>{
        'Name' => 'Checklist 2',
        'Value' => 'val2',
        'SequenceNo' => 3,
        'DefaultValue' => 'def2',
        'AdditionalValue' => 'Extra',
        'IsMainHeading' => 'false',
        'IsHeading' => 'false',
        'IsSubLabel' => 'true',
        'colSpan' => 1,
        'colSpan2' => 1,
        'sequenceVisible' => 'false',
        'AdditionalVisible' => 'false',
        'Disclaimer' => 'true'
    }
});

    // Create Unit_Bundle__c
    Unit_Bundle__c bundle = new Unit_Bundle__c(
        Name = 'Test Bundle',
        Opportunity__c = opp.Id,
        Negotiation_Checklist__c = checklistJson
       
    );
    insert bundle;


        // Create Site_Visit__c
        Site_Visit__c sv = new Site_Visit__c(Name='Visit 1', Opportunity__c = opp.Id, Unit_Bundle__c = bundle.Id);
        insert sv;
        PageReference ref = Page.SiteVisitQuotePdf;
		ref.getParameters().put('id',bundle.Id);
        Test.startTest();
        DocumentGeneration gen = new DocumentGeneration();
        gen.GenerateSiteVisitQuotePdf(bundle.Id, opp.Id, sv.Id);
        Test.stopTest();

        List<ContentVersion> conList = [SELECT Id FROM ContentVersion WHERE Title = 'Site Visit Proposal.pdf'];
       // System.assertEquals(1, conList.size(), 'Site Visit Proposal PDF should be inserted');
    }

    static testMethod void testGenerateSiteVisitInspectionpdf() {
           RecordType rc = [SELECT Id, Name, DeveloperName, SObjectType 
FROM RecordType 
WHERE SObjectType = 'Account' 
AND DeveloperName = 'PersonAccount'];
		 Account acc = new Account(LastName='Test Name',RecordTypeId = rc.Id);
        insert acc;
	Map<String, Id> rtMap = new Map<String, Id>();
        for (RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Enquiry__c']) {
            rtMap.put(rt.DeveloperName, rt.Id);
        }
    // Create Enquiry__c with the RecordType
    Enquiry__c enquiry = new Enquiry__c(
        Name = 'Test Enquiry',
        RecordTypeId = rtMap.get('Landlord'),
        Status__c = 'New', 
    	Email__c = 'test@example.com',
        Contact_Person__c = acc.Id,
        Mobile__c='1234567890'
    );
    insert enquiry;

    // Create Opportunity__c
    Opportunity__c opp = new Opportunity__c(
        Name = 'Test Opportunity',
        Account_Name__c = acc.Id,
        Enquiry__c = enquiry.Id
    );
    insert opp;
        
	String Name = 'Test Negotiation_Checklist__c';
            String Value = 'qwerty';
            Integer SequenceNo = 2;
            String DefaultValue = 'abcd';
    String checklistJSON = JSON.serialize(new List<Object>{
    new Map<String, Object>{
        'Name' => Name,
        'Value' => Value,
        'SequenceNo' => SequenceNo,
        'DefaultValue' => DefaultValue,
        'AdditionalValue' => 'Test',
        'IsMainHeading' => 'true',
        'IsHeading' => 'true',
        'IsSubLabel' => 'true',
        'colSpan' => 2,
        'colSpan2' => 3,
        'sequenceVisible' => 'true',
        'AdditionalVisible' => 'true',
        'Disclaimer' => 'false'
    },
    new Map<String, Object>{
        'Name' => 'Checklist 2',
        'Value' => 'val2',
        'SequenceNo' => 3,
        'DefaultValue' => 'def2',
        'AdditionalValue' => 'Extra',
        'IsMainHeading' => 'false',
        'IsHeading' => 'false',
        'IsSubLabel' => 'true',
        'colSpan' => 1,
        'colSpan2' => 1,
        'sequenceVisible' => 'false',
        'AdditionalVisible' => 'false',
        'Disclaimer' => 'true'
    }
});

    // Create Unit_Bundle__c
    Unit_Bundle__c bundle = new Unit_Bundle__c(
        Name = 'Test Bundle',
        Opportunity__c = opp.Id,
        Negotiation_Checklist__c = checklistJson
       
    );
    insert bundle;

        // Create Site_Visit__c
        Site_Visit__c sv = new Site_Visit__c(Name='Visit 1', Opportunity__c = opp.Id, Unit_Bundle__c = bundle.Id);
        insert sv;


        Test.startTest();
        DocumentGeneration gen = new DocumentGeneration();
        gen.GenerateSiteVisitInspectionpdf(opp.Id, sv.Id);
        Test.stopTest();

        //List<ContentVersion> conList = [SELECT Id FROM ContentVersion WHERE Title = 'FeedBack Form.pdf'];
        //System.assertEquals(1, conList.size(), 'Feedback Form PDF should be inserted');
    }
}