force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Reason_for_Closed__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Closed__c</fullName>
    <label>Reason for Closed</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Test Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Size_in_sqfts__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqfts__c</fullName>
    <label>Size (in sqft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/recordTypes/Tenant.recordType-meta.xml
<RecordType>
    <fullName>Tenant</fullName>
    <active>true</active>
    <label>Tenant</label>
</RecordType>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Size_in_sqfts__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqfts__c</fullName>
    <label>Size (in sqfts.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnquiryOpportunityQueueableTest.cls
@isTest
public class EnquiryOpportunityQueueableTest {

    @isTest
    static void testQueueableExecution() {
      
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Enquiry__c' AND Name = 'Tenant' LIMIT 1];

 
        Account acc = new Account(Name = 'Test Account');
        insert acc;

     
        Contact c = new Contact(
            LastName = 'Test Contact',
            AccountId = acc.Id
            
        );
        insert c;

     
        List<Enquiry__c> enquiryList = new List<Enquiry__c>{
            new Enquiry__c(
                Name = 'Test Enquiry 1',
                Status__c = 'Closed',
                Reason_for_Closed__c = 'Qualified',
                Mobile__c = '9876543210',
                RecordTypeId = rt.Id,
                Size_in_sqfts__c = 2500,
                Size_in_sqft__c = 'below 10000',
                Type_of_Unit__c = 'Land'
                
                
            ),
            new Enquiry__c(
                Name = 'Test Enquiry 2',
                Status__c = 'Closed',
                Reason_for_Closed__c = 'Qualified',
                Mobile__c = '9123456789',
                RecordTypeId = rt.Id,
                 Size_in_sqfts__c = 3000,
                Size_in_sqft__c = 'below 10000',
                Type_of_Unit__c = 'Land'
                
              
            )
        };
        insert enquiryList;

        EnquiryOpportunityQueueable queueJob = new EnquiryOpportunityQueueable(enquiryList);

        Test.startTest();
        System.enqueueJob(queueJob);
        Test.stopTest();

       
        List<Opportunity__c> opps = [
            SELECT Id, Name, Stage__c 
            FROM Opportunity__c 
            WHERE Enquiry__c IN :enquiryList
        ];


        for (Opportunity__c opp : opps) {
            System.assertEquals('Qualified', opp.Stage__c, 'Stage should be Qualified');
        }
    }
}