force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit Bundles</relationshipLabel>
    <relationshipName>Unit_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Shortlist by customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShortListBundleMessageController.cls
public class ShortListBundleMessageController{
    private ApexPages.StandardController standardController;
    public Datetime siteVisitDate { get; set; }
    
    Public ShortListBundleMessageController(ApexPages.StandardController standardController) {
        string unitBundleId = ApexPages.currentPage().getParameters().get('Id');
    }
    
    public PageReference updateUnitBundleStatus()
    {
        string unitBundleId = ApexPages.currentPage().getParameters().get('Id');
        system.debug('unitBundleId'+unitBundleId);
        if(unitBundleId != null && unitBundleId != ''){
            Unit_Bundle__c unitBundle =[SELECT Id,Opportunity__c,
                                        Opportunity__r.Account_Name__c,
                                        Opportunity__r.Enquiry__c,
                                        Opportunity__r.Enquiry__r.Name,
                                        Opportunity__r.Account_Name__r.PersonEmail
                                        FROM Unit_Bundle__c
                                        WHERE Id = : unitBundleId];
            if(siteVisitDate != null)
            {
                System.debug('siteVisitDate'+siteVisitDate);
                if(siteVisitDate < system.today())
                {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, System.label.Error_Message_For_Site_Visit_Past));
                    return null;
                }
                else
                {
                    Site_Visit__c siteVisit = New Site_Visit__c();
                    siteVisit.Unit_Bundle__c = unitBundleId;
                    siteVisit.Visit_Date_Time__c = siteVisitDate;
                    siteVisit.Name = unitBundle.Opportunity__r.Enquiry__r.Name+' '+ String.valueOf(siteVisitDate); 
                    siteVisit.Opportunity__c = unitBundle.Opportunity__c;
                    siteVisit.Enquiry__c = unitBundle.Opportunity__r.Enquiry__c;
                    siteVisit.Account__c = unitBundle.Opportunity__r.Account_Name__c ;
                    insert siteVisit;
                    List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
                    List<EmailTemplate> emailTemp = [Select Id, Subject, Description, HtmlValue, DeveloperName, Body from EmailTemplate 
                                                     where DeveloperName =: 'Template_for_Informing_about_Scheduling_Site_Visit_to_Tenant' limit 1];
                    OrgWideEmailAddress OWEA = [SELECT Id, Address From OrgWideEmailAddress
                                                WHERE Address =: System.label.Site_Mail ];

                    if(unitBundle.Opportunity__r.Account_Name__r.PersonEmail != null && unitBundle.Opportunity__r.Account_Name__r.PersonEmail != '')
                    {
                        system.debug('emailTemp'+emailTemp.size());
                        system.debug('email'+unitBundle.Opportunity__r.Account_Name__r.PersonEmail );
                        Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemp[0].Id, null, siteVisit.Id);
                        mail.setToAddresses(new List<String>{unitBundle.Opportunity__r.Account_Name__r.PersonEmail });
                        mail.setSaveAsActivity(true);
                        mail.setOrgWideEmailAddressId(OWEA.id);
                        mails.add(mail);  
                      
                        if(!mails.isEmpty()){
                            system.debug('50');
                            try{
                               // Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                                System.debug('Mail Sent:'+mail);
                            }
                            catch (Exception e) {
                                System.debug('Problem sending Email: '+ e.getMessage());
                            }
                        }
                    }
                    
                    unitBundle.Status__c = 'Shortlist by customer';
                    update unitBundle;
                    PageReference pr = new PageReference('/apex/ShortListBundleMessage');
                    pr.setRedirect(true);               
                    return pr;
                }
                
            }
            else
            {
                return null;
            }
        }
        else
        {
            return null;
        }
    }
    
}