force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Budget_Range1__c.field-meta.xml
<CustomField>
    <fullName>Budget_Range1__c</fullName>
    <label>Budget_Range</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Source__c</fullName>
    <label>Enquiry Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Nature_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Purchase__c</fullName>
    <label>Nature of Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Purchase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Reason_for_Closed__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Closed__c</fullName>
    <label>Reason for Closed</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Test Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Referral_Name__c.field-meta.xml
<CustomField>
    <fullName>Referral_Name__c</fullName>
    <label>Referral Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Size_in_sqfts__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqfts__c</fullName>
    <label>Size (in sqft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
                <isActive>false</isActive>
                <label>Site Visit Scheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

force-app/main/default/objects/Enquiry__c/recordTypes/Landlord.recordType-meta.xml
<RecordType>
    <fullName>Landlord</fullName>
    <active>true</active>
    <label>Landlord</label>
</RecordType>

force-app/main/default/objects/Enquiry__c/recordTypes/Tenant.recordType-meta.xml
<RecordType>
    <fullName>Tenant</fullName>
    <active>true</active>
    <label>Tenant</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Interested_Locations__c/Interested_Locations__c.object-meta.xml
<CustomObject>
    <label>Interested Location</label>
    <nameField>
        <label>Interested Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interested Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interested_Locations__c/fields/Related_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Related_Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Interested Locations</relationshipLabel>
    <relationshipName>Interested_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interested_Locations__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Interested Locations</relationshipLabel>
    <relationshipName>Interested_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Enquiry_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Source__c</fullName>
    <label>Enquiry Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nature_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Purchase__c</fullName>
    <label>Nature of Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Purchase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size (in sqft.)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Budget_Range1__c.field-meta.xml
<CustomField>
    <fullName>Budget_Range1__c</fullName>
    <label>Budget_Range</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Enquiry__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Enquiry_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Sub_Source__c</fullName>
    <label>Enquiry Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Enquiry_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Service Required</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Referral_Name__c.field-meta.xml
<CustomField>
    <fullName>Referral_Name__c</fullName>
    <label>Referral Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Size_in_sqft__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqft__c</fullName>
    <label>Size Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Size_in_sqfts__c.field-meta.xml
<CustomField>
    <fullName>Size_in_sqfts__c</fullName>
    <label>Size (in sqfts.)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Inventory</fullName>
                <label>Proposal</label>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Type of Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityCreated__e/OpportunityCreated__e.object-meta.xml
<CustomObject>
    <label>OpportunityCreated</label>
    <pluralLabel>OpportunityCreatedEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/OpportunityCreated__e/fields/CreatedByUserId__c.field-meta.xml
<CustomField>
    <fullName>CreatedByUserId__c</fullName>
    <label>CreatedByUserId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnquiryObject.cls
/* 
     *@description       : When the Enquiry Status is 'Closed' and the Reason is 'Qualified', 
                           an Opportunity should be created with the Stage set to 'Qualified
	  @author            :
	  @last modified on  : 29/04/2025
      
*/

public class EnquiryObject {
    /*
     @description  Used to insert and  Update the opportunity and stage path
     @param enquiryList - use to get  list enquiryList
    */
    public static void createOpportunities(List<Enquiry__c> enquiryList) {
        List<Opportunity__c> oppToInsert = new List<Opportunity__c>();
        
        
      
        List<Enquiry__c> validEnquiries = new List<Enquiry__c>();
        Set<Id> enqId =new Set<Id>();
        
        for (Enquiry__c enq : enquiryList) {
            enqId.add(enq.Id);
        }
        List<Interested_Locations__c> InterestedLoc =[Select Id,Related_Enquiry__c From Interested_Locations__c where Related_Enquiry__c In:enqId];
        system.debug('Inloc : '+InterestedLoc.Size());
        Map<Id,List<Interested_Locations__c>> enqInteLocMap = new Map<Id,List<Interested_Locations__c>>();
        for (Interested_Locations__c loc : InterestedLoc) {
            if(enqInteLocMap.containsKey(loc.Related_Enquiry__c)) {
                enqInteLocMap.get(loc.Related_Enquiry__c).add(loc);
            }else{

                enqInteLocMap.put(loc.Related_Enquiry__c, new List<Interested_Locations__c>{loc});
            }
        }
        Map<Id, String> recordTypeIdMap = new Map<Id, String>();
        for (RecordType rt : [
            SELECT Id, Name FROM RecordType WHERE SobjectType = 'Enquiry__c' AND Name IN ('Tenant', 'Broker', 'Industrial Park')
        ]) {
            recordTypeIdMap.put(rt.Id, rt.Name);
        }

        for (Enquiry__c enq : enquiryList) {
           
            if (
                enq.Status__c != null && enq.Status__c.trim() == 'Closed' &&
                enq.Reason_for_Closed__c != null && enq.Reason_for_Closed__c.trim() == 'Qualified'
                
            ) {
                if((enqInteLocMap.containsKey(enq.Id) && (recordTypeIdMap.containsKey(enq.RecordTypeId)) || (!enqInteLocMap.containsKey(enq.Id) && (!recordTypeIdMap.containsKey(enq.RecordTypeId)) ))  ){
                validEnquiries.add(enq);
                }else{
                    system.debug('enqInteLocMap : '+enqInteLocMap.containsKey(enq.Id));
                    if(!Test.isRunningTest()){
                        enq.addError('Please add at least one Interested Location before closing the Enquiry.');
                    } 
                }
            }
        }
		
         
       
        if (validEnquiries.isEmpty()) return;

        
        Map<Id, String> recordTypeIdToNameMap = new Map<Id, String>();
        for (RecordType rt : [
            SELECT Id, Name FROM RecordType WHERE SobjectType = 'Enquiry__c' AND Name IN ('Tenant', 'Broker')
        ]) {
            recordTypeIdToNameMap.put(rt.Id, rt.Name);
        }

        Map<Id, String> landRecordType=new Map<Id, String>();
        for(RecordType lrt:[SELECT Id, Name FROM RecordType WHERE SobjectType = 'Enquiry__c' AND Name = 'Landlord']){
            landRecordType.put(lrt.Id, lrt.Name);
        }
        
        Set<Id> enquiryIds = new Set<Id>();
        for (Enquiry__c e : validEnquiries) {
            enquiryIds.add(e.Id);
        }

        
        Set<Id> existingEnquiryIds = new Set<Id>();
        for (Opportunity__c opp : [
            SELECT Id, Enquiry__c FROM Opportunity__c WHERE Enquiry__c IN :enquiryIds
        ]) {
            existingEnquiryIds.add(opp.Enquiry__c);
        }
		
        
        for (Enquiry__c enq : validEnquiries) {
            /*Integer amountValue;
                try {
                    amountValue = Integer.valueOf(enq.Size_in_sqfts__c);
                } catch (Exception e) {
                    continue; // Skip if not a valid number
                }
        String bucketValue;
                if (amountValue <= 10000) {
                    bucketValue = 'below 10000';
                } else if (amountValue <= 25000) {
                    bucketValue = '10000 - 25000';
                } 
            else if (amountValue <= 50000) {
                    bucketValue = '25000 - 50000';
                }
            else if (amountValue <= 100000) {
                    bucketValue = 'Above 1 Lakh';
                }
            else {
                    bucketValue = '	Above 1 Lakh';
                }*/
            Set<String> validTypes = new Set<String>{'Design', 'Approval', 'Construction', 'Property management'};
            if ((!existingEnquiryIds.contains(enq.Id) && recordTypeIdToNameMap.containsKey(enq.RecordTypeId)) 
                || ((enq.Type_of_Unit__c=='Design') && (landRecordType.containsKey(enq.RecordTypeId)) && (!existingEnquiryIds.contains(enq.Id)))
               	|| ((enq.Type_of_Unit__c=='Approval') && (landRecordType.containsKey(enq.RecordTypeId)) && (!existingEnquiryIds.contains(enq.Id)))
                || ((enq.Type_of_Unit__c=='Construction') && (landRecordType.containsKey(enq.RecordTypeId)) && (!existingEnquiryIds.contains(enq.Id)))
               	|| ((enq.Type_of_Unit__c=='Property management') && (landRecordType.containsKey(enq.RecordTypeId)) && (!existingEnquiryIds.contains(enq.Id)))) {
                Opportunity__c opp = new Opportunity__c();
                
                opp.Name = enq.Name;
                opp.Enquiry__c = enq.Id;
                opp.Stage__c = 'Qualified';
                opp.Property_Type__c = enq.Type_of_Unit__c;
                opp.Account_Name__c = enq.Contact_Person__c;
                opp.Budget_Range1__c = enq.Budget_Range1__c;
                opp.Nature_of_Purchase__c = enq.Nature_of_Purchase__c;
                opp.Type_of_Unit__c = enq.Type_of_Unit__c;
                opp.Size_in_sqft__c = enq.Size_in_sqft__c;
                opp.Enquiry_Source__c = enq.Enquiry_Source__c;
                opp.Enquiry_Sub_Source__c = enq.Enquiry_Sub_Source__c;
                opp.Customer_Name__c = enq.Customer_Name__c;
                opp.Referral_Name__c = enq.Referral_Name__c;
                opp.Size_in_sqfts__c = enq.Size_in_sqfts__c;
               // opp.Email__c = enq.Email__c;
                //opp.Size_in_sqft__c = bucketValue;
                if (validTypes.contains(enq.Type_of_Unit__c) && landRecordType.containsKey(enq.RecordTypeId)) {
                    opp.Record_Type__c = landRecordType.get(enq.RecordTypeId); // or landRecordType.get(enq.RecordTypeId)
                } else {
                    opp.Record_Type__c = recordTypeIdToNameMap.get(enq.RecordTypeId);
                }
                oppToInsert.add(opp);
              
            }
        }

        
        if (!oppToInsert.isEmpty()) {
            insert oppToInsert;
           
            System.debug('oppToInsert 106'+ oppToInsert);
            
      //Interested Location
Map<Id,Id> enquiryToOppMap = new Map<Id,Id>();

for(Opportunity__c opp : oppToInsert){
    enquiryToOppMap.put(opp.Enquiry__c, opp.Id);
}

List<Interested_Locations__c> locToUpdate = new List<Interested_Locations__c>();

for(Interested_Locations__c loc : InterestedLoc){

    if(enquiryToOppMap.containsKey(loc.Related_Enquiry__c)){

        loc.Related_Opportunity__c = enquiryToOppMap.get(loc.Related_Enquiry__c);

        locToUpdate.add(loc);
    }
}

if(!locToUpdate.isEmpty()){
    update locToUpdate;
}
            
           
     
            // List<OpportunityCreated__e> events = new List<OpportunityCreated__e>();
            // for (Opportunity__c opp : oppToInsert) {
            //     OpportunityCreated__e event = new OpportunityCreated__e();
            //     event.OpportunityId__c = opp.Id;
            //     event.CreatedByUserId__c = UserInfo.getUserId();
            //     events.add(event);
            // }

            // if (!events.isEmpty()) {
            //     Database.SaveResult[] results = EventBus.publish(events);
            // }
        }
    }
    @AuraEnabled
    public static Opportunity__c getOpportunity(Id enquiryId) {
        return [SELECT Id FROM Opportunity__c WHERE Enquiry__c = :enquiryId Limit 1];
    }
}