force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/No_of_People_Planned__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_Planned__c</fullName>
    <label>No of People (Planned)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Status__c</fullName>
    <formula>TEXT( Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Visit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <formula>DATEVALUE( Visit_Date_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit Bundles</relationshipLabel>
    <relationshipName>Unit_Bundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SiteVisitPDFController.cls
public class SiteVisitPDFController{
    
    public List<Site_Visit__c> visits {get;set;}
    public Map<Id, List<ContentVersion>> visitImages {get;set;}
    public List<PageWrapper> pages {get;set;}
    
    public class PageWrapper { 
        public Site_Visit__c visit {get;set;}
        public ContentVersion img1 {get;set;}
        public ContentVersion img2 {get;set;}
        public Integer pageNumber {get;set;}
        public Boolean isLastPage {get;set;}
    }
    
    public SiteVisitPDFController(){
        
        Id oppId = ApexPages.currentPage().getParameters().get('oppId');
        if(oppId == null) return;
        
        visits = [SELECT Id, Name, Unit_Bundle__r.Name,Enquiry__r.Name, Opportunity__r.Name,Visit_Date_Time__c, Site_Visit_Status__c, No_of_People_Planned__c
                  FROM Site_Visit__c
                  WHERE Opportunity__c = :oppId AND Site_Visit_Status__c = 'Completed'AND Visit_Date__c = TODAY  ORDER BY CreatedDate ASC];
        
        if(visits.isEmpty()) return;
        
        Set<Id> visitIds = new Set<Id>();
        for(Site_Visit__c v : visits){
            visitIds.add(v.Id);
        }
        
        List<ContentDocumentLink> links = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :visitIds];
        
        Set<Id> docIds = new Set<Id>();
        for(ContentDocumentLink l : links){
            docIds.add(l.ContentDocumentId);
        }
        
        List<ContentVersion> versions = [SELECT Id, ContentDocumentId, CreatedDate FROM ContentVersion WHERE ContentDocumentId IN :docIds ];
        
        Map<Id, List<ContentVersion>> docMap = new Map<Id, List<ContentVersion>>();
        
        for(ContentVersion v : versions){
            if(!docMap.containsKey(v.ContentDocumentId)){
                docMap.put(v.ContentDocumentId, new List<ContentVersion>());
            }
            docMap.get(v.ContentDocumentId).add(v);
        }
        
        visitImages = new Map<Id, List<ContentVersion>>();
        
        for(ContentDocumentLink l : links){
            if(!visitImages.containsKey(l.LinkedEntityId)){
                visitImages.put(l.LinkedEntityId, new List<ContentVersion>());
            }
            if(docMap.containsKey(l.ContentDocumentId)){
                visitImages.get(l.LinkedEntityId).addAll(docMap.get(l.ContentDocumentId));
            }
        }
        
        pages = new List<PageWrapper>();
        Integer pg = 1;
        
        for(Site_Visit__c v : visits){
            
            List<ContentVersion> imgs = visitImages.get(v.Id);
            
            PageWrapper p = new PageWrapper();
            p.visit = v;
            
            if(imgs != null && !imgs.isEmpty()){
                p.img1 = imgs[0];
                if(imgs.size() > 1){
                    p.img2 = imgs[1];
                }
            }
            p.pageNumber = pg;
            pg++;
            pages.add(p);
        }
        if(!pages.isEmpty()){
            pages[pages.size()-1].isLastPage = true;
        }
    }
}