force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/No_of_People_Planned__c.field-meta.xml
<CustomField>
    <fullName>No_of_People_Planned__c</fullName>
    <label>No of People (Planned)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Resource_Allocator__c.field-meta.xml
<CustomField>
    <fullName>Resource_Allocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A Resource Allocator (User Lookup) field is added to the Site Visit to assign a responsible resource during scheduling.</description>
    <inlineHelpText>Select the responsible user to whom this Site Visit is assigned.</inlineHelpText>
    <label>Resource Allocator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Google_Coordinates_Link__c.field-meta.xml
<CustomField>
    <fullName>Google_Coordinates_Link__c</fullName>
    <label>Google Coordinates Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SiteVisitTriggerHandler.cls
public class SiteVisitTriggerHandler {

    public static void processSiteVisits(List<Site_Visit__c> newList, Map<Id, Site_Visit__c> oldMap){

        List<Site_Visit__c> validRecords = new List<Site_Visit__c>();

        // Filter records (Insert + Update condition)
        for(Site_Visit__c sv : newList){

            // INSERT
            if(oldMap == null){
                if(sv.Resource_Allocator__c != null){
                    validRecords.add(sv);
                }
            }
            // UPDATE
            else{
                Site_Visit__c oldSv = oldMap.get(sv.Id);

                if(sv.Resource_Allocator__c != oldSv.Resource_Allocator__c && sv.Resource_Allocator__c != null){
                    validRecords.add(sv);
                }
            }
        }

        if(validRecords.isEmpty()) return;

        Set<Id> bundleIds = new Set<Id>();
        Set<Id> userIds = new Set<Id>();

        for(Site_Visit__c sv : validRecords){
            if(sv.Unit_Bundle__c != null){
                bundleIds.add(sv.Unit_Bundle__c);
            }
            userIds.add(sv.Resource_Allocator__c);
        }

        //Get Users
        Map<Id, User> userMap = new Map<Id, User>(
            [SELECT Id, Name, Email FROM User WHERE Id IN :userIds]
        );

        //Get Unit Bundles
        Map<Id, Unit_Bundle__c> bundleMap = new Map<Id, Unit_Bundle__c>(
            [SELECT Id, Linked_Unit__c FROM Unit_Bundle__c WHERE Id IN :bundleIds]
        );

        //Parse JSON → Shortlisted Unit IDs
        Set<Id> shortlistedUnitIds = new Set<Id>();

        for(Unit_Bundle__c bundle : bundleMap.values()){
            if(bundle.Linked_Unit__c != null){
                List<Object> ids = (List<Object>) JSON.deserializeUntyped(bundle.Linked_Unit__c);
                for(Object obj : ids){
                    shortlistedUnitIds.add((Id)obj);
                }
            }
        }

        if(shortlistedUnitIds.isEmpty()) return;

        //Get Shortlisted Units
        Map<Id, Shortlisted_Unit__c> shortlistedMap = new Map<Id, Shortlisted_Unit__c>(
            [SELECT Id, Unit__c FROM Shortlisted_Unit__c WHERE Id IN :shortlistedUnitIds]
        );

        //Get Unit IDs
        Set<Id> unitIds = new Set<Id>();

        for(Shortlisted_Unit__c su : shortlistedMap.values()){
            if(su.Unit__c != null){
                unitIds.add(su.Unit__c);
            }
        }

        if(unitIds.isEmpty()) return;

        //Get Unit Details         
        Map<Id, Unit__c> unitMap = new Map<Id, Unit__c>(
            [SELECT Id,
                    Point_of_Contact__r.Name,
                    Point_of_Contact__r.PersonEmail,
                    Point_of_Contact__r.PersonMobilePhone,
                    Google_Coordinates_Link__c
             FROM Unit__c
             WHERE Id IN :unitIds]
        );

        //Prepare Emails (ONE EMAIL PER SITE VISIT)
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Site_Visit__c sv : validRecords){

            if(!userMap.containsKey(sv.Resource_Allocator__c)) continue;

            String toEmail = userMap.get(sv.Resource_Allocator__c).Email;

            //Combine all unit details into one email
            String combinedBody = '';

            for(Unit__c unit : unitMap.values()){

                combinedBody += 'Landlord Name: ' + unit.Point_of_Contact__r.Name + '\n'
                              + 'Mobile: ' + unit.Point_of_Contact__r.PersonMobilePhone + '\n'
                              + 'Email: ' + unit.Point_of_Contact__r.PersonEmail + '\n'
                              + 'Location: ' + unit.Google_Coordinates_Link__c + '\n\n';
            }

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            mail.setToAddresses(new List<String>{toEmail});
            mail.setSubject('Site Visit Scheduled');

            String body = 'Dear ' + userMap.get(sv.Resource_Allocator__c).Name + ',\n\n'
                        + 'You have been assigned a Site Visit. Please find the details below:\n\n'
                        + combinedBody
                        + 'Site Visit Date & Time: ' + String.valueOf(sv.Visit_Date_Time__c) + '\n'
                        + 'No. of Persons Accompanying: ' + String.valueOf(sv.No_of_People_Planned__c) + '\n\n'
                        + 'Please proceed with the inspection accordingly.\n\n'
                        + 'Best Regards,\nTeam';

            mail.setPlainTextBody(body);

            emails.add(mail);
        }

       
        if(!emails.isEmpty() && !Test.isRunningTest()){
            Messaging.sendEmail(emails);
        }
    }
}