force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Advance_Security_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Advance_Security_Deposit__c</fullName>
    <label>Advance Security Deposit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Building_Type__c.field-meta.xml
<CustomField>
    <fullName>Building_Type__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>PEB</fullName>
            </value>
            <value>
                <fullName>RCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Canopy_available__c.field-meta.xml
<CustomField>
    <fullName>Canopy_available__c</fullName>
    <label>Canopy available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Center_Height__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Center_Height__c</fullName>
    <label>Ceiling Center Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Center_Height_UOM__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Center_Height_UOM__c</fullName>
    <label>Ceiling Center Height UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Side_Height__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Side_Height__c</fullName>
    <label>Ceiling Clear Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Ceiling_Side_Height_UOM__c.field-meta.xml
<CustomField>
    <fullName>Ceiling_Side_Height_UOM__c</fullName>
    <label>Ceiling Side Height UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Dock_Leveller__c.field-meta.xml
<CustomField>
    <fullName>Dock_Leveller__c</fullName>
    <label>Dock Leveller</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/EoT_Crane_Provision__c.field-meta.xml
<CustomField>
    <fullName>EoT_Crane_Provision__c</fullName>
    <label>EoT Crane Provision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <label>Escalation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fire_Noc_available__c.field-meta.xml
<CustomField>
    <fullName>Fire_Noc_available__c</fullName>
    <label>Fire Noc available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fire_Safety__c.field-meta.xml
<CustomField>
    <fullName>Fire_Safety__c</fullName>
    <label>Fire Safety</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Extinguishers</fullName>
            </value>
            <value>
                <fullName>Hydrants</fullName>
            </value>
            <value>
                <fullName>Sprinklers</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor_ht_from_ground_level__c.field-meta.xml
<CustomField>
    <fullName>Floor_ht_from_ground_level__c</fullName>
    <label>Floor ht from ground level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor_ht_from_ground_level_UOM__c.field-meta.xml
<CustomField>
    <fullName>Floor_ht_from_ground_level_UOM__c</fullName>
    <label>Floor ht from ground level UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Flooring_Strength_per_MT__c.field-meta.xml
<CustomField>
    <fullName>Flooring_Strength_per_MT__c</fullName>
    <label>Flooring Strength (per MT)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/No_of_shutters__c.field-meta.xml
<CustomField>
    <fullName>No_of_shutters__c</fullName>
    <label>No of shutters</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Office_space_available__c.field-meta.xml
<CustomField>
    <fullName>Office_space_available__c</fullName>
    <label>Office space available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Power_available__c.field-meta.xml
<CustomField>
    <fullName>Power_available__c</fullName>
    <label>Power available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Rent_per_uom_Price_per_uom__c.field-meta.xml
<CustomField>
    <fullName>Rent_per_uom_Price_per_uom__c</fullName>
    <label>Rent per uom/ Price per uom</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/SIDCO_SIPCOT_CAM_or_Addl_Charges__c.field-meta.xml
<CustomField>
    <fullName>SIDCO_SIPCOT_CAM_or_Addl_Charges__c</fullName>
    <label>SIDCO / SIPCOT / CAM or Addl Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c.field-meta.xml
<CustomField>
    <fullName>SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c</fullName>
    <description>SIDCO/SIPCOT/CAMorAddl Charges SqFt/SqMt</description>
    <label>SIDCO/SIPCOT/CAM/Addl Charges SqFt/SqMt</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_UOM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_Rent_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Rent_Total_Price__c</fullName>
    <formula>Saleable_Area__c * Rent_per_uom_Price_per_uom__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Chargeable Area * Rent / Price Per UOM</inlineHelpText>
    <label>Total Rent/ Total Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SiteVisitQuotePdfController.cls
public class SiteVisitQuotePdfController {
    public List<Unit_Bundle__c> unitBundles{get;set;}
    public Opportunity opp{get;set;}
    public List<Unit__c> shortListUnits{get;set;}
    public List<String> internalImageUrlList{get;set;}
    public List<String> externalImageUrlList{get;set;}
    
    public SiteVisitQuotePdfController(){
        String unitBundleId = ApexPages.CurrentPage().getparameters().get('id');
        Set<Id> shortListIdSet = New Set<Id>();                                                                          
        Set<Id> unitIdSet = New Set<Id>();
        externalImageUrlList = New List<String>();
        internalImageUrlList = New List<String>();
        SObjectAccessDecision decisionbuilderopediaUnitBundle = Security.stripInaccessible(AccessType.READABLE,
                                                                                           [SELECT Id, Name, Linked_Unit__c
                                                                                            FROM Unit_Bundle__c
                                                                                            WHERE Id =: unitBundleId]);
        if(!(decisionbuilderopediaUnitBundle.getRecords()).isEmpty() ){
            unitBundles = (List<Unit_Bundle__c>) decisionbuilderopediaUnitBundle.getRecords();
            for(Unit_Bundle__c unitBundle:unitBundles){
                List<String> shortlistedUnitIds = (List<String>) JSON.deserialize(unitBundle.Linked_Unit__c, List<String>.class);
                for(String shortListId: shortlistedUnitIds){
                    shortListIdSet.add(shortListId);
                }
            }
            system.debug('shortListIdSet'+shortListIdSet);
            
            SObjectAccessDecision decisionbuilderopediaUnit = Security.stripInaccessible(AccessType.READABLE,
                                                                                         [SELECT Id, Name,
                                                                                          Building_Type__c,
                                                                                          Ceiling_Side_Height__c,
                                                                                          Ceiling_Side_Height_UOM__c,
                                                                                          Ceiling_Center_Height__c,
                                                                                          Ceiling_Center_Height_UOM__c,
                                                                                          Flooring_Strength_per_MT__c,
                                                                                          Floor_ht_from_ground_level__c,
                                                                                          Floor_ht_from_ground_level_UOM__c,
                                                                                          No_of_shutters__c,
                                                                                          Fire_Noc_available__c,
                                                                                          Fire_Safety__c,
                                                                                          Power_available__c,
                                                                                          Rent_per_uom_Price_per_uom__c,
                                                                                          Total_Rent_Total_Price__c,
                                                                                          SIDCO_SIPCOT_CAM_or_Addl_Charges__c,
                                                                                          SIDCO_SIPCOT_CAM_or_Addl_Charges_UOM__c,
                                                                                          City__c,
                                                                                          Canopy_available__c,
                                                                                          Dock_Leveller__c,
                                                                                          Advance_Security_Deposit__c,
                                                                                          EoT_Crane_Provision__c,
                                                                                          Office_space_available__c,
                                                                                          Escalation__c,
                                                                                          (SELECT Id, Name 
                                                                                                           FROM Shortlisted_Units__r)
                                                                                          FROM Unit__c
                                                                                          WHERE Id IN  (
                                                                                              SELECT Unit__c 
                                                                                              FROM Shortlisted_Unit__c 
                                                                                              WHERE Id IN :shortListIdSet
                                                                                          )]);
            
            
            if(!(decisionbuilderopediaUnit.getRecords()).isEmpty() ){
                shortListUnits = (List<Unit__c>) decisionbuilderopediaUnit.getRecords();
                for(Unit__c unit:shortListUnits){
                    system.debug('unit'+unit);
                    unitIdSet.add(unit.id);
                }
            }
            system.debug('unitIdSet'+unitIdSet);
            if(!unitIdSet.isEmpty())
            {
                List<contentVersion> contentVersionList =[SELECT ID,ContentDocumentId,FirstPublishLocationId,
                                                          title
                                                          FROM contentVersion
                                                          WHERE FirstPublishLocationId  IN:unitIdSet
                                                          AND Document_Type__c = 'Internal Images'];
                List<contentVersion> contentVersionExternalList =[SELECT ID,ContentDocumentId,FirstPublishLocationId,
                                                                  title
                                                                  FROM contentVersion
                                                                  WHERE FirstPublishLocationId  IN:unitIdSet
                                                                  AND Document_Type__c = 'External Images'];
                system.debug('contentVersionList'+contentVersionList);
                system.debug('contentVersionExternalList--> '+contentVersionExternalList);
                Map<ID,List<String>> mapOfContentVersion = New  Map<ID,List<String>>(); 
                Map<ID,List<String>> mapOfExternalContentVersion = New  Map<ID,List<String>>(); 
                for(contentVersion thisCV:contentVersionList)
                {
                    String imageURL = '/sfc/servlet.shepherd/version/download/'  +thisCV.id;
                    system.debug('imageURL--> '+imageURL);
                    internalImageUrlList.add(imageURL);
                    system.debug('internalImageUrlList--> '+internalImageUrlList);
                    
                    /*if(mapOfContentVersion.containsKey(thisCV.FirstPublishLocationId))
                    {    List <String>  internalList = New List <String> ();
                     internalList =mapOfContentVersion.get(thisCV.FirstPublishLocationId);
                     String imageURL = '/sfc/servlet.shepherd/version/download/'  +thisCV.id;
                     internalList.add(imageURL);
                     mapOfContentVersion.put(thisCV.FirstPublishLocationId,internalList);
                    }
                    else
                    {
                        String imageURL = '/sfc/servlet.shepherd/version/download/'  +thisCV.id;
                        mapOfContentVersion.put(thisCV.FirstPublishLocationId, New List <String> {imageURL});
                    }*/
                }
                for(contentVersion thisCV2:contentVersionExternalList)
                {
                    String imageURL = '/sfc/servlet.shepherd/version/download/'  +thisCV2.id;
                    system.debug('imageURL--> '+imageURL);
                    externalImageUrlList.add(imageURL);
                    system.debug('externalImageUrlList--> '+externalImageUrlList);
                    
                    /*if(mapOfExternalContentVersion.containsKey(thisCV2.FirstPublishLocationId))
                    {    List <String>  internalList = New List <String> ();
                     internalList =mapOfExternalContentVersion.get(thisCV2.FirstPublishLocationId);
                     String imageURL = '/sfc/servlet.shepherd/version/download/'  +thisCV2.id;
                     internalList.add(imageURL);
                     mapOfExternalContentVersion.put(thisCV2.FirstPublishLocationId,internalList);
                    }
                    else
                    {
                        String imageURL = '/sfc/servlet.shepherd/version/download/'  +thisCV2.id;
                        mapOfExternalContentVersion.put(thisCV2.FirstPublishLocationId, New List <String> {imageURL});
                    }*/
                }
                
                system.debug('mapOfContentVersion'+mapOfContentVersion);
                system.debug('mapOfExternalContentVersion--> '+mapOfExternalContentVersion);
            }
        }
    }
}