force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <formula>TEXT( Unit__r.Unit_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tower_Block__c/Tower_Block__c.object-meta.xml
<CustomObject>
    <label>Tower/Block</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers/Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Floor</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower_Block__c.field-meta.xml
<CustomField>
    <fullName>Tower_Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower/Block</label>
    <referenceTo>Tower_Block__c</referenceTo>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Type_of_Unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Unit__c</fullName>
    <label>Service Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Category__c.field-meta.xml
<CustomField>
    <fullName>Unit_Category__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Available for lease</fullName>
                <isActive>false</isActive>
                <label>Available for lease</label>
            </value>
            <value>
                <fullName>Available for sales</fullName>
                <isActive>false</isActive>
                <label>Available for sales</label>
            </value>
            <value>
                <fullName>Available for sales/lease</fullName>
                <isActive>false</isActive>
                <label>Available for sales/lease</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>On lease</fullName>
                <isActive>false</isActive>
                <label>On lease</label>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
                <isActive>false</isActive>
                <label>Shortlisted</label>
            </value>
            <value>
                <fullName>Sold</fullName>
                <isActive>false</isActive>
                <label>Sold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ShowRelatedUnitHandler.cls
/**
 * @description This class is used in ShowRelatedUnit LWC Component
 */
public without sharing class ShowRelatedUnitHandler {

    /**
     * @description This method is used to show all the units that exists in unit bumdle
     * @param unitBundleId
     * @param baseURL
     * @return data in json format
     */
    @Auraenabled(cacheable=true)
    public static String getUnits(String unitBundleId, String baseURL) {
        // Strip fields that are not readable
        SObjectAccessDecision decision = Security.stripInaccessible(
                                            AccessType.READABLE,
                                            [SELECT Id, Linked_Unit__c
                                                FROM Unit_Bundle__c 
                                                WHERE Id =: unitBundleId]);

        if(!(decision.getRecords()).isEmpty()) {
            List<Unit_Bundle__c> unitBundelList = (List<Unit_Bundle__c>) decision.getRecords();
            Unit_Bundle__c unitBundle = unitBundelList[0];
            
            List<Map<String,Object>> unitMapList = new List<Map<String,Object>>();
            if(!String.isBlank(unitBundle.Linked_Unit__c)){
                List<String> shortListedUnits = (List<String>) JSON.deserialize(unitBundle.Linked_Unit__c,List<String>.class);

                SObjectAccessDecision decisionShortlistedUnit = Security.stripInaccessible(
                                            AccessType.READABLE,
                                            [SELECT Id, Unit__c, Unit__r.Tower_Block__c,
                                                Unit__r.Name, Unit_Status__c,
                                                Unit__r.Tower_Block__r.Name, Unit__r.Floor__c,
                                                Unit__r.Type_of_Unit__c, Unit__r.Unit_Category__c
                                                FROM Shortlisted_Unit__c
                                                WHERE Id In: shortListedUnits
                                                ORDER BY Unit__r.Unit_Category__c, Unit__r.Name ASC
                                            ]);

                if(!(decisionShortlistedUnit.getRecords()).isEmpty()) {
                    for(Shortlisted_Unit__c shortListedUnit: (List<Shortlisted_Unit__c>) decisionShortlistedUnit.getRecords()){
                        Map<String,Object> unitMap = new Map<String,Object>();
                        String url = baseURL +'/lightning/r/Unit__c/'+shortListedUnit.Unit__c+'/view';
                        unitMap.put('URL',url);
                        unitMap.put('Id',shortListedUnit.Unit__c);
                        unitMap.put('Name',shortListedUnit.Unit__r.Name);
                        unitMap.put('TowerName',shortListedUnit.Unit__r.Tower_Block__r.Name);
                        unitMap.put('Floor',shortListedUnit.Unit__r.Floor__c);
                        unitMap.put('Status',shortListedUnit.Unit_Status__c);
                        unitMap.put('Type_Of_Unit',shortListedUnit.Unit__r.Type_of_Unit__c);
                        unitMap.put('Unit_Category',shortListedUnit.Unit__r.Unit_Category__c);
                        unitMapList.add(unitMap);
                    }
                }
            }
            return JSON.serialize(unitMapList);
        }
        return null;
    }
}