force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Date_Available__c.field-meta.xml
<CustomField>
    <fullName>Date_Available__c</fullName>
    <label>Date Available</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SendEmailtoLandLord.cls
public class SendEmailtoLandLord {
    
    @InvocableMethod(label='SendEmailtoLandLord' description='Send Email to LandLord')
    public static void getUnitRecords(List<InputWrapper> input) {
        Set<String> UnitIds = new Set<String>();
        String visitDate = input[0].VisitDateTime;
        String unitbundles = input[0].UnitBundleId;
        
        //UnitBundleId = (List<UnitBundle>) JSON.deserialize(jsonData, List<UnitBundle>.class);
        List<Unit_Bundle__c> unitbundle = [SELECT Id,Linked_Unit__c FROM Unit_Bundle__c Where Id = : unitbundles  limit 1];
        
        if(!unitbundle.isEmpty() && String.isNotBlank(unitbundle[0].Linked_Unit__c)){
            List<String> ShortlistIds = (List<String>) JSON.deserialize(unitbundle[0].Linked_Unit__c , List<String>.class);
            List<Shortlisted_Unit__c> shortList = [SELECT Id,Unit__c FROM Shortlisted_Unit__c where Id in : ShortlistIds ];
            for(Shortlisted_Unit__c shortlistunit : shortList){
                UnitIds.add(shortlistunit.Unit__c);
            }
            
        }
        
       
        List<Unit__c> units = [SELECT Id, City__c,Point_of_Contact__r.PersonEmail , Date_Available__c, Name FROM Unit__c where Id in : UnitIds];
        system.debug('units :'+units.size());
        
        
        // List<Site_Visit__c> visits = 
        // [select id, Visit_Date_Time__c from Site_Visit__c  WHERE Id IN :siteVisitIds];
        // system.debug('visits : ' + visits.size());
         OrgWideEmailAddress owea = [
    SELECT Id
    FROM OrgWideEmailAddress
    WHERE Address = 'chennai@allwarehouses.in'
    LIMIT 1
];
        
        EmailTemplate  emails =  [SELECT Id,DeveloperName,Body,HtmlValue,Subject from EmailTemplate where DeveloperName  ='Template_for_Informing_about_Scheduling_Site_Visit_to_Landlord' Limit 1 ]; 
        
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        
        for (Unit__c unit : units) {
            system.debug('unit :'+unit);
            system.debug('unit.Point_of_Contact__r.PersonEmail :'+unit.Point_of_Contact__r.PersonEmail);
            if(unit.Point_of_Contact__c != null && 
             String.isNotBlank(unit.Point_of_Contact__r.PersonEmail)) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new list<string>{unit.Point_of_Contact__r.PersonEmail});
               // mail.setCcAddresses(new List<String>{ 'pooja@allwarehouses.in', 'chennai@allwarehouses.in' });
                mail.setCcAddresses(new List<String>{ 'chennai@allwarehouses.in' });
                 mail.setOrgWideEmailAddressId(owea.Id);
                string html = emails.HtmlValue.replace('#City',unit.City__c);
                
                string body =emails.Body.replace('#City',unit.City__c);
                String subject = emails.Subject;
                
                html = html.replace('#VisitDate', visitDate);
                body = body.replace('#VisitDate', visitDate);
                
                subject = subject.replace('#VisitDate',visitDate);
                mail.setHtmlBody(body);
                mail.setSubject(subject);
                mail.setPlainTextBody(html);
                // mail.setTargetObjectId(unit.Id);[$City] 
                // mail.setTreatTargetObjectAsRecipient(false);
                mail.setSaveAsActivity(true); 
                emailsToSend.add(mail);
            }
        }
        if (!emailsToSend.isEmpty()) {
            system.debug('emailsToSend : '+emailsToSend);
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailsToSend);
            
        }
    }
    public class InputWrapper {
       // @InvocableVariable(required=true)
        //public List<String> UnitIds;
        
        @InvocableVariable
        public String VisitDateTime;
        @InvocableVariable
        public String UnitBundleId;
        
       
       
        
    }
    
}