force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <label>Site Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GetUnitDetails.cls
public without sharing class GetUnitDetails {

    public class RequestWrapper {
        @InvocableVariable(required=true)
        public Id siteVisitId;
    }

    public class ResponseWrapper {
        @InvocableVariable
        public Id unitId;
    }

    @InvocableMethod(label='Get Unit Details')
    public static List<ResponseWrapper> getUnitDetails(List<RequestWrapper> requests) {

        List<ResponseWrapper> responseList = new List<ResponseWrapper>();

        if(requests == null || requests.isEmpty()){
            return responseList;
        }

        Id siteVisitId = requests[0].siteVisitId;

        List<Site_Visit__c> siteVisits = [
            SELECT Id, Unit_Bundle__c
            FROM Site_Visit__c
            WHERE Id = :siteVisitId
            LIMIT 1
        ];
        system.debug('siteVisits'+siteVisits);

        if(siteVisits.isEmpty()){
            return responseList;
        }

        Set<Id> bundleIds = new Set<Id>();

        for(Site_Visit__c sv : siteVisits){
            if(sv.Unit_Bundle__c != null){
                bundleIds.add(sv.Unit_Bundle__c);
            }
        }
         system.debug('bundleIds'+bundleIds);

        if(bundleIds.isEmpty()){
            return responseList;
        }

        List<Unit_Bundle__c> bundles = [
            SELECT Id, Linked_Unit__c
            FROM Unit_Bundle__c
            WHERE Id IN :bundleIds
        ];

        Set<Id> shortlistedUnitIds = new Set<Id>();

        for(Unit_Bundle__c bundle : bundles){

            if(bundle.Linked_Unit__c != null){

                List<Object> ids =
                    (List<Object>)JSON.deserializeUntyped(
                        bundle.Linked_Unit__c
                    );

                for(Object obj : ids){
                    shortlistedUnitIds.add((Id)obj);
                }
            }
        }
        system.debug('shortlistedUnitIds'+shortlistedUnitIds);

        if(shortlistedUnitIds.isEmpty()){
            return responseList;
        }

        List<Shortlisted_Unit__c> shortlistedUnits = [
            SELECT Id, Unit__c
            FROM Shortlisted_Unit__c
            WHERE Id IN :shortlistedUnitIds
        ];

        for(Shortlisted_Unit__c su : shortlistedUnits){

            if(su.Unit__c != null){

                ResponseWrapper res = new ResponseWrapper();

                res.unitId = su.Unit__c;

                responseList.add(res);

                break;
                system.debug('res'+res);
            }
           
        }
       

        return responseList;
    }
    
}