force-app/main/default/objects/Shortlisted_Unit__c/Shortlisted_Unit__c.object-meta.xml
<CustomObject>
    <label>Shortlisted Unit</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shortlisted Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shortlisted Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Shortlisted_Unit__c/fields/Unit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Unit_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Bundle</label>
    <referenceTo>Unit_Bundle__c</referenceTo>
    <relationshipLabel>Shortlisted Units</relationshipLabel>
    <relationshipName>Shortlisted_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Unit_Category__c.field-meta.xml
<CustomField>
    <fullName>Unit_Category__c</fullName>
    <label>Property Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/Unit_Bundle__c.object-meta.xml
<CustomObject>
    <label>Unit Bundle</label>
    <nameField>
        <label>Unit Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Bundle__c/fields/Linked_Unit__c.field-meta.xml
<CustomField>
    <fullName>Linked_Unit__c</fullName>
    <label>Linked Unit</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Unit_Bundle__c/fields/Number_Of_Base_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Base_Units__c</fullName>
    <label>Number Of Base Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RemoveUnitFromUnitBundle.cls
public class RemoveUnitFromUnitBundle {
    @InvocableMethod(label='Remove Unit From Unit Bundle' description='Remove Unit From Unit Bundle')
    public static List<Response> execute(list<Request> reqs){
        List<Unit_Bundle__c> unitBundles = new List<Unit_Bundle__c>();
        List<Response> responseList = new List<Response>();
        
        for(Request req: reqs){
            Set<String> shortlistedUnits = new Set<String>();

            List<Object> relatedUnits = (List<Object>) JSON.deserializeuntyped(req.unitBundleObj.Linked_Unit__c);
            
            for(Object obj: relatedUnits){
                if((String) obj != req.shortUnitID){
                    shortlistedUnits.add((String) obj);
                }
            }
            
            Boolean errorOccurred = false;
            if(!shortlistedUnits.isEmpty()){
                List<Shortlisted_Unit__c> shortListedUnitList = [SELECT Id
                                                             	FROM Shortlisted_Unit__c
                                                              	WHERE ID In: shortlistedUnits
                                                              	AND Unit__r.Unit_Category__c !=: System.Label.Unit_Category_Parking
                                                             ];
                
                if(shortListedUnitList.isEmpty()){
                    errorOccurred = true;
                }
            }else{
                errorOccurred = true;
            }
            
            List<String> linkedUnits = new List<String>();
            if(errorOccurred == false){
                for(Object obj: relatedUnits){
                    if((String) obj != req.shortUnitID){
                        linkedUnits.add((String) obj);
                    }
                }
                
                req.unitBundleObj.Linked_Unit__c = JSON.serialize(linkedUnits);
                req.unitBundleObj.Number_Of_Base_Units__c = linkedUnits.size();
                unitBundles.add(req.unitBundleObj);
            }
            
            Response resp = new Response();
            resp.showError = errorOccurred;
            responseList.add(resp);
        }
        
        if(!unitBundles.isEmpty()){
            update unitBundles;
        }
        
        return responseList;
    }
    
    public class Response{
        @invocableVariable(label='Show Error' description='Show Error')
        public Boolean showError;
    }
    
    public class Request{
        @invocableVariable(label='Shortlisted Unit ID' description='Shortlisted Unit ID')
        public String shortUnitID;
        
        @invocableVariable(label='Unit Bundle Object' description='Unit Bundle Object')
        public Unit_Bundle__c unitBundleObj;
    }
}