force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventCalendarController.cls
public with sharing class EventCalendarController {
    @AuraEnabled
    public static String createEvent(String eventValues, String selectedUsersJson) {
        Map<String, Object> eventInput = (Map<String, Object>) JSON.deserializeUntyped(eventValues);

        // Parse selected users JSON to a list of maps
        List<Object> selectedUsersList = (List<Object>) JSON.deserializeUntyped(selectedUsersJson);
        System.debug('Selected Users List: ' + selectedUsersList);

        String startRaw = (String) eventInput.get('StartDateTime');
        String endRaw   = (String) eventInput.get('EndDateTime');

        // Replace T with space, remove milliseconds and timezone
        String startStr = startRaw.replace('T', ' ').substring(0, 19);
        String endStr   = endRaw.replace('T', ' ').substring(0, 19);

        // Create the Event
        Event__c evt = new Event__c(
            Subject__c = String.valueOf(eventInput.get('Subject')),
            StartDateTime__c = DateTime.valueOfGmt(startStr),
            EndDateTime__c = DateTime.valueOfGmt(endStr),
            All_Day_Event__c = Boolean.valueOf(eventInput.get('AllDay')),
            OwnerId = UserInfo.getUserId(),
            Location__c = String.valueOf(eventInput.get('Location')),
            Description__c = String.valueOf(eventInput.get('Description'))
        );
        insert evt;

        // Create attendee records
        List<Event_Attendee__c> attendees = new List<Event_Attendee__c>();
        for (Object userObj : selectedUsersList) {
            Map<String, Object> userMap = (Map<String, Object>) userObj;
            attendees.add(new Event_Attendee__c(
                Name = (String) userMap.get('Name'),
                Event__c = evt.Id,
                Event_Attendee__c = (Id) userMap.get('Id')
            ));
        }

        if (!attendees.isEmpty()) {
            insert attendees;
        }

        return evt.Id;
    }
}